import {selectModel} from './helpers';
import {test,expect} from '@playwright/test';
import {openSettings,closeSettings,readMap,focus,importMap} from './helpers';
import {fixture} from '../fixture';
test('64 atom map: manual friction, pinned drag, state drop position, reload and semantic zoom',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await importMap(page,fixture());await expect(page.locator('canvas.map')).toHaveAttribute('data-nodes','56');
 await focus(page,'Музыка',false);await page.mouse.move(640,360);await page.mouse.down();await page.mouse.move(540,270,{steps:12});await page.mouse.up();let saved=await readMap(page);const hub=saved.atoms.find(a=>a.id==='hub-0')!;expect(hub.pinned).toBe(true);expect(hub.x).toBeCloseTo(-100,0);expect(hub.y).toBeCloseTo(-90,0);
 await focus(page,'Мысль 0-0',false);await page.mouse.move(640,360);await page.mouse.down();await page.mouse.move(740,450,{steps:12});await page.mouse.up();saved=await readMap(page);const moved=saved.atoms.find(a=>a.id==='leaf-0-0')!;expect(moved.state).toBe('normal');expect(moved.pinned).toBe(false);expect(moved.spatial.resistance).toBeGreaterThan(0);await page.waitForTimeout(900);const later=(await readMap(page)).atoms.find(a=>a.id===moved.id)!;expect(Math.hypot(later.x-moved.x,later.y-moved.y)).toBeLessThan(2);
 await focus(page,'Музыка',false);await page.mouse.move(640,360);await page.mouse.down();await page.mouse.move(610,310,{steps:5});const zone=page.locator('[data-state="now"]');await expect(zone).toBeVisible();const box=(await zone.boundingBox())!;await page.mouse.move(box.x+box.width/2,box.y+box.height/2,{steps:10});await page.mouse.up();await expect(zone).toBeHidden();saved=await readMap(page);const now=saved.atoms.find(a=>a.id==='hub-0')!;expect(now.state).toBe('now');expect(now.x).toBe(hub.x);expect(now.y).toBe(hub.y);
 await page.reload();await focus(page,'Музыка',false);await page.locator('canvas.map').click({position:{x:640,y:360},button:'right'});await expect(page.getByRole('button',{name:'Открепить',exact:true})).toBeVisible();await page.getByRole('button',{name:'Закрыть меню атома'}).click();for(let i=0;i<5;i++)await page.getByRole('button',{name:'Отдалить',exact:true}).click();await expect.poll(async()=>Number(await page.locator('canvas.map').getAttribute('data-nodes'))).toBeLessThan(56);await page.screenshot({path:'artifacts/cluster-map.png'});expect(errors).toEqual([]);
});
test('automatic exact links, fuzzy suggestions, rejection and off mode survive reload',async({page})=>{
 await page.goto('/');for(const title of ['Graphology','Юрий']){await page.locator('canvas.map').press('n');await page.getByRole('textbox',{name:'Название',exact:true}).fill(title);await page.getByRole('button',{name:'Сохранить',exact:true}).click();}
 await openSettings(page);await page.getByLabel('Режим автосвязей',{exact:true}).selectOption('automatic');await closeSettings(page);await page.locator('canvas.map').press('n');await page.getByRole('textbox',{name:'Название',exact:true}).fill('Исследование');await page.getByRole('textbox',{name:'Текст',exact:true}).fill('Grapholigy и Юрий');await expect(page.getByRole('button',{name:'+ Graphology',exact:false})).toBeVisible();await page.getByRole('button',{name:'Сохранить',exact:true}).click();let data=await readMap(page);expect(data.links).toHaveLength(1);expect(data.links[0].source).toBe('automatic');
 await focus(page,'Исследование');await page.getByText('Связи',{exact:true}).click();await page.getByRole('button',{name:'Удалить связь с Юрий'}).click();await page.getByRole('button',{name:'Сохранить',exact:true}).click();await expect(page.getByRole('dialog',{name:'Редактор атома'})).toBeHidden();expect((await readMap(page)).links).toHaveLength(0);await page.reload();await focus(page,'Исследование');await page.getByRole('button',{name:'Сохранить',exact:true}).click();expect((await readMap(page)).links).toHaveLength(0);
 await openSettings(page);await page.getByLabel('Режим автосвязей',{exact:true}).selectOption('off');await selectModel(page,'Молекула');await page.getByLabel('Закрепление атомов',{exact:true}).uncheck();await closeSettings(page);await focus(page,'Юрий');await expect(page.getByRole('button',{name:'Закрепить',exact:true})).toBeHidden();await page.getByRole('button',{name:'Закрыть редактор'}).click();await page.reload();await openSettings(page);await expect(page.getByLabel('Режим автосвязей',{exact:true})).toHaveValue('off');await expect(page.getByRole('button',{name:'Молекула',exact:true})).toHaveAttribute('aria-pressed','true');await expect(page.getByLabel('Закрепление атомов',{exact:true})).not.toBeChecked();
});
