import {test,expect} from '@playwright/test';
import {makeAtom,makeLink} from '../../src/core/model';
import {graphModel} from '../../src/graph/model';
import {importMap,readMap,openSettings,closeSettings} from './helpers';
test('hundred atoms: branch drag, group pin/state, stable zoom and reload',async({page})=>{
 test.setTimeout(90000);await page.goto('/');await expect(page.locator('canvas.map')).toBeVisible();
 const atoms=Array.from({length:100},(_,i)=>makeAtom({id:'a'+i,title:i<4?'Project '+i:'Thought '+i,created_at:'2026-01-01T00:00:00Z'})),links=[];for(let i=1;i<88;i++)links.push(makeLink('a'+Math.floor((i-1)/4),'a'+i,'related','context'));links.push(makeLink('a18','a61'),makeLink('a27','a79'));links.forEach((l,i)=>l.id='branch-link-'+String(i).padStart(3,'0'));await importMap(page,{atoms,links});
 await page.getByRole('button',{name:'К центру карты',exact:true}).click();await page.waitForTimeout(1000);await page.screenshot({animations:'disabled',path:'artifacts/branches-100.png'});
 // Pin the fixture to isolate camera invariance from an independently moving simulation.
 const before=await readMap(page);await page.locator('canvas.map').hover();await page.mouse.wheel(0,-70);await page.waitForTimeout(250);const after=await readMap(page);expect(after.atoms.map(a=>a.id)).toEqual(before.atoms.map(a=>a.id));
 const map=graphModel(after,'all',.3,'');const group=map.nodes.find(n=>n.members&&n.members.length>=3)!;expect(group).toBeTruthy();
  await page.getByRole('button',{name:'Открыть поиск',exact:true}).click();await page.getByRole('textbox',{name:'Поиск',exact:true}).fill(group.label);await page.locator('.search-results button').first().click();await expect(page.locator('main')).toHaveAttribute('data-navigation','idle');await page.locator('canvas.map').focus();await page.keyboard.press('Escape');
 for(let i=0;i<4;i++)await page.getByRole('button',{name:'Отдалить',exact:true}).click();
 // Center projection uses the same branch centroid; capture current source coordinates for its screen position.
 const snapshot=await readMap(page),projection=graphModel(snapshot,'all',.4096,'');const target=projection.nodes.find(n=>n.id===group.id)!;const focused=snapshot.atoms.find(a=>a.title===group.label)!;
 const camera=await page.evaluate(()=>Object.values(history.state).find((v:any)=>v?.camera&&v?.lens) as {camera:{x:number;y:number;zoom:number}});const x=640+target.x*camera.camera.zoom+camera.camera.x,y=360+target.y*camera.camera.zoom+camera.camera.y;await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+50,y+25,{steps:12});await page.mouse.up();await page.waitForTimeout(250);
 const dragged=await readMap(page);const delta=target.members!.map(id=>{const a=snapshot.atoms.find(a=>a.id===id)!,b=dragged.atoms.find(a=>a.id===id)!;return{x:b.x-a.x,y:b.y-a.y};});expect(Math.abs(delta[0].x)).toBeGreaterThan(20);expect(Math.max(...delta.map(d=>d.x))-Math.min(...delta.map(d=>d.x))).toBeLessThan(3);
 await page.mouse.click(x+50,y+25,{button:'right'});await expect(page.getByRole('dialog',{name:'Действия с ветвью'})).toBeVisible();await page.getByRole('button',{name:'Закрепить',exact:true}).click();const pinned=await readMap(page);expect(target.members!.every(id=>pinned.atoms.find(a=>a.id===id)?.pinned)).toBe(true);
 await page.screenshot({animations:'disabled',path:'artifacts/branch-detail.png'});await page.reload();await expect(page.locator('canvas.map')).toBeVisible();const restored=await readMap(page);for(const id of target.members!)expect(restored.atoms.find(a=>a.id===id)).toMatchObject(pinned.atoms.find(a=>a.id===id)!);
 await page.mouse.click(x+50,y+25,{button:'right'});await page.getByRole('button',{name:'Пауза',exact:true}).click();const paused=await readMap(page);expect(paused.atoms.filter(a=>a.state==='paused').map(a=>a.id).sort()).toEqual([...target.members!].sort());await page.mouse.click(x+50,y+25,{button:'right'});await page.getByRole('button',{name:'Удалить…',exact:true}).click();await expect(page.getByRole('dialog',{name:'Действия с ветвью'})).toContainText(`Удалить ${target.members!.length} атомов`);await page.getByRole('button',{name:'Удалить ветвь',exact:true}).click();const deleted=await readMap(page);expect(deleted.atoms).toHaveLength(100-target.members!.length);expect(deleted.atoms.every(a=>!target.members!.includes(a.id))).toBe(true);
});
