import {test,expect} from '@playwright/test';
import {openSettings,closeSettings} from './helpers';
test('daily checklist, kanban, day history, reload and plugin toggle keep progress',async({page})=>{
 await page.clock.setFixedTime(new Date(2026,8,25,12));await page.goto('/');await expect(page.locator('canvas')).toBeVisible();
 await openSettings(page);await page.getByRole('button',{name:'Плагины →',exact:true}).click();
 const plugin=page.locator('.plugin-row').filter({hasText:'Ежедневные задачи'});await plugin.getByRole('button',{name:'Включить',exact:true}).click();await closeSettings(page);
 const open=async()=>{await page.getByRole('button',{name:'Меню карты',exact:true}).click();await page.getByRole('button',{name:'Ежедневные задачи',exact:true}).click();};
 await open();const dialog=page.getByRole('dialog',{name:'Ежедневные задачи',exact:true});
 await dialog.getByRole('textbox',{name:'Новая ежедневная задача'}).fill('Читать 20 минут');await dialog.getByRole('button',{name:'Добавить',exact:true}).click();
 await dialog.getByRole('button',{name:'Выполнить: Читать 20 минут',exact:true}).click();await expect(dialog.getByText('1 из 1 выполнено',{exact:true})).toBeVisible();
 await expect(dialog.locator('meter').last()).toHaveAttribute('value','100');
 await dialog.getByRole('button',{name:'Канбан',exact:true}).click();await expect(dialog.locator('.task-column').filter({has:page.getByRole('heading',{name:'Готово',exact:true})})).toContainText('Читать 20 минут');
 await page.screenshot({path:'artifacts/daily-tasks-desktop.png'});
 await dialog.getByRole('button',{name:'Закрыть',exact:true}).click();await page.clock.setFixedTime(new Date(2026,8,26,12));await open();await expect(dialog.getByText('0 из 1 выполнено',{exact:true})).toBeVisible();
 await dialog.getByRole('button',{name:'Предыдущий день',exact:true}).click();await expect(dialog.getByText('1 из 1 выполнено',{exact:true})).toBeVisible();
 await page.reload();await expect(page.locator('canvas')).toBeVisible();await open();await expect(dialog.getByText('0 из 1 выполнено',{exact:true})).toBeVisible();
 await dialog.getByRole('button',{name:'Предыдущий день',exact:true}).click();await expect(dialog.getByText('1 из 1 выполнено',{exact:true})).toBeVisible();
 await dialog.getByRole('button',{name:'Закрыть',exact:true}).click();await openSettings(page);await page.getByRole('button',{name:'Плагины →',exact:true}).click();await plugin.getByRole('button',{name:'Выключить',exact:true}).click();await plugin.getByRole('button',{name:'Включить',exact:true}).click();await closeSettings(page);await open();
 await dialog.getByRole('button',{name:'Предыдущий день',exact:true}).click();await expect(dialog.getByText('1 из 1 выполнено',{exact:true})).toBeVisible();
 await page.setViewportSize({width:390,height:844});await dialog.getByRole('button',{name:'Канбан',exact:true}).click();await expect(dialog).toBeVisible();expect(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await page.screenshot({path:'artifacts/daily-tasks-mobile.png'});
});
