import {test,expect} from '@playwright/test';
import {openSettings,closeSettings,focus} from './helpers';
test('direct adapter writes native file handles and refuses concurrent edits',async({page})=>{
 await page.goto('/');await expect(page.locator('canvas.map')).toBeVisible();
 await page.evaluate(async()=>{const root=await navigator.storage.getDirectory(),folder=await root.getDirectoryHandle('direct-test',{create:true}),file=await folder.getFileHandle('Native.md',{create:true}),stream=await file.createWritable();await stream.write('---\ncustom: keep\n---\nOriginal body');await stream.close();(window as any).showDirectoryPicker=async()=>folder;});
 await openSettings(page);await page.getByRole('button',{name:'Подключить Obsidian Vault',exact:true}).click();await expect(page.locator('footer')).toContainText('1 атомов');await closeSettings(page);await focus(page,'Native');await page.getByRole('button',{name:'Редактировать',exact:true}).click();await page.getByRole('textbox',{name:'Текст',exact:true}).fill('Written from Phosphora');await page.getByRole('button',{name:'Сохранить',exact:true}).click();await openSettings(page);await page.getByRole('button',{name:'Синхронизировать · direct-test',exact:true}).click();
 const read=()=>page.evaluate(async()=>{const root=await navigator.storage.getDirectory();return (await (await (await root.getDirectoryHandle('direct-test')).getFileHandle('Native.md')).getFile()).text();});await expect.poll(read).toContain('Written from Phosphora');expect(await read()).toContain('phosphored_id:');expect(await read()).toContain('custom: keep');
 await closeSettings(page);await focus(page,'Native');await page.getByRole('button',{name:'Редактировать',exact:true}).click();await page.getByRole('textbox',{name:'Текст',exact:true}).fill('Local concurrent edit');await page.getByRole('button',{name:'Сохранить',exact:true}).click();await page.evaluate(async()=>{const folder=await (await navigator.storage.getDirectory()).getDirectoryHandle('direct-test'),file=await folder.getFileHandle('Native.md'),stream=await file.createWritable();await stream.write('External concurrent edit');await stream.close();});await openSettings(page);await page.getByRole('button',{name:'Синхронизировать · direct-test',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Конфликт');expect(await read()).toBe('External concurrent edit');
});
