import {test,expect,type Page} from '@playwright/test';
import {readMap,importMap} from './helpers';
import {makeAtom,makeLink} from '../../src/core/model';
async function save(page:Page,title:string,text=''){await page.getByRole('textbox',{name:'Название',exact:true}).fill(title);if(text)await page.getByRole('textbox',{name:'Текст',exact:true}).fill(text);await page.getByRole('button',{name:'Сохранить',exact:true}).click();await expect(page.getByRole('dialog')).toBeHidden();}
async function enable(page:Page,name:string){await page.getByRole('button',{name:'Меню карты'}).click();await page.getByRole('button',{name:'Настройки и резервные копии'}).click();await page.getByRole('button',{name:'Плагины →'}).click();await page.locator('.plugin-row').filter({hasText:name}).getByRole('button',{name:'Включить',exact:true}).click();await page.getByRole('button',{name:'Закрыть настройки'}).click();}
test('empty long press creates at its world point and text edits directly',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.locator('canvas')).toBeVisible();await expect(page.getByRole('button',{name:'+ Создать',exact:true})).toHaveCount(0);
 await page.mouse.move(750,430);await page.mouse.down();await page.waitForTimeout(600);await expect(page.getByRole('dialog')).toBeHidden();await page.mouse.up();await expect(page.getByRole('dialog',{name:'Редактор атома'})).toBeVisible();await save(page,'Long press','Tap this text');
 const data=await readMap(page);expect(data.atoms).toHaveLength(1);expect(data.atoms[0].x).toBeCloseTo(110,0);expect(data.atoms[0].y).toBeCloseTo(70,0);
 await page.locator('canvas').click({position:{x:750,y:430}});await page.locator('.markdown').getByText('Tap this text').click();await expect(page.getByRole('textbox',{name:'Текст',exact:true})).toBeFocused();await page.getByRole('textbox',{name:'Текст',exact:true}).fill('Edited by tap');await page.getByRole('button',{name:'Сохранить',exact:true}).click();expect((await readMap(page)).atoms[0].content).toBe('Edited by tap');await page.locator('canvas').focus();for(let i=0;i<12;i++)await page.keyboard.press('-');await expect.poll(async()=>Number(await page.locator('canvas').getAttribute('data-zoom'))).toBeLessThan(.2);await page.screenshot({animations:'disabled',path:'artifacts/single-atom-far-zoom.png'});expect(errors).toEqual([]);
});
test('lasso selects multiple atoms and grouped actions affect only the selection',async({page})=>{
 await page.goto('/');await page.locator('canvas').press('n');await save(page,'One');await page.locator('canvas').press('n');await save(page,'Two');await enable(page,'Волшебное лассо');
 await page.keyboard.down('Shift');await page.mouse.move(530,250);await page.mouse.down();for(const [x,y] of [[750,250],[750,470],[530,470],[530,250]])await page.mouse.move(x,y,{steps:6});await page.mouse.up();await page.keyboard.up('Shift');await expect(page.getByRole('dialog')).toBeHidden();await page.mouse.move(640,360);await page.mouse.down();await page.waitForTimeout(600);await expect(page.getByRole('dialog')).toBeHidden();await page.mouse.up();await expect(page.getByRole('dialog',{name:'Действия с атомом'})).toContainText('Выделено: 2');await page.getByRole('dialog',{name:'Действия с атомом'}).getByRole('button',{name:'Сейчас',exact:true}).click();expect((await readMap(page)).atoms.every(a=>a.state==='now')).toBe(true);
 await page.mouse.move(960,360);await page.mouse.down();await page.waitForTimeout(600);await expect(page.getByRole('dialog')).toBeHidden();await page.mouse.up();await expect(page.getByRole('dialog',{name:'Редактор атома'})).toBeVisible();await save(page,'Destination');await page.mouse.move(640,360);await page.mouse.down();await page.waitForTimeout(600);await page.mouse.up();await page.getByRole('dialog',{name:'Действия с атомом'}).getByRole('button',{name:'В другую группу…'}).click();await page.getByRole('dialog',{name:'Действия с ветвью'}).getByRole('button',{name:'Destination',exact:true}).click();const moved=await readMap(page);const destination=moved.atoms.find(a=>a.title==='Destination')!;expect(moved.links.filter(l=>l.from===destination.id&&l.relation==='grouped')).toHaveLength(2);
});
test('deleting a workspace switches safely, preserves the other map and removes its OPFS pool',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.locator('canvas').press('n');await save(page,'Keep');await page.getByRole('button',{name:'Выбрать хранилище'}).click();await expect(page.getByRole('button',{name:'Удалить текущее хранилище…'})).toBeDisabled();await page.getByRole('button',{name:'Новое хранилище',exact:true}).click();await page.getByRole('textbox',{name:'Название хранилища',exact:true}).fill('Disposable');await page.getByRole('button',{name:'Создать и открыть'}).click();await expect(page.locator('.workspace-switch')).toContainText('Disposable');await page.locator('canvas').press('n');await save(page,'Delete me');
 await page.getByRole('button',{name:'Выбрать хранилище'}).click();await page.getByRole('button',{name:'Удалить текущее хранилище…'}).click();await expect(page.getByRole('button',{name:'Удалить безвозвратно'})).toBeDisabled();await page.getByRole('textbox',{name:'Название для удаления'}).fill('Disposable');await page.getByRole('button',{name:'Удалить безвозвратно'}).click();await expect(page.locator('.workspace-switch')).toContainText('Основное');expect((await readMap(page)).atoms.map(a=>a.title)).toEqual(['Keep']);
 const directories=await page.evaluate(async()=>{const names:string[]=[];for await(const name of (await navigator.storage.getDirectory() as any).keys())names.push(name);return names;});expect(directories.filter(n=>n.startsWith('.phosphored-'))).toEqual([]);expect(errors).toEqual([]);
 await page.getByRole('button',{name:'Выбрать хранилище'}).click();await page.getByRole('button',{name:'Новое хранилище',exact:true}).click();await page.getByRole('textbox',{name:'Название хранилища',exact:true}).fill('Survivor');await page.getByRole('button',{name:'Создать и открыть'}).click();await expect(page.locator('.workspace-switch')).toContainText('Survivor');await page.locator('canvas').press('n');await save(page,'Survives root deletion');await page.getByRole('button',{name:'Выбрать хранилище'}).click();await page.locator('.workspace-list button').filter({hasText:'Основное'}).click();await expect(page.locator('.workspace-switch')).toContainText('Основное');await page.getByRole('button',{name:'Выбрать хранилище'}).click();await page.getByRole('button',{name:'Удалить текущее хранилище…'}).click();await page.getByRole('textbox',{name:'Название для удаления'}).fill('Основное');await page.getByRole('button',{name:'Удалить безвозвратно'}).click();await expect(page.locator('.workspace-switch')).toContainText('Survivor');expect((await readMap(page)).atoms.map(a=>a.title)).toEqual(['Survives root deletion']);await page.reload();await page.getByRole('button',{name:'Выбрать хранилище'}).click();await expect(page.locator('.workspace-list button').filter({hasText:'Основное'})).toHaveCount(0);expect(errors).toEqual([]);
});
test('ambient lens keeps all atoms and coordinates; disabling it restores filtering',async({page})=>{
 await page.goto('/');await expect(page.locator('canvas')).toBeVisible();const atoms=[makeAtom({title:'Now',state:'now',x:-150}),makeAtom({title:'Later',x:150}),makeAtom({title:'Archived',state:'archived',y:180})];await importMap(page,{atoms,links:[]});await enable(page,'Мягкие линзы');await page.getByRole('navigation',{name:'Линзы карты'}).getByRole('button',{name:'Сейчас',exact:true}).click();await expect(page.locator('canvas')).toHaveAttribute('data-nodes','3');expect((await readMap(page)).atoms.map(a=>[a.id,a.x,a.y])).toEqual(atoms.map(a=>[a.id,a.x,a.y]));await page.screenshot({animations:'disabled',path:'artifacts/ambient-lens.png'});
 await page.getByRole('button',{name:'Меню карты'}).click();await page.getByRole('button',{name:'Настройки и резервные копии'}).click();await page.getByRole('button',{name:'Плагины →'}).click();await page.locator('.plugin-row').filter({hasText:'Мягкие линзы'}).getByRole('button',{name:'Выключить',exact:true}).click();await page.getByRole('button',{name:'Закрыть настройки'}).click();await expect(page.locator('canvas')).toHaveAttribute('data-nodes','1');
});
test('dropping an expanded atom in Now never changes the other member of its branch',async({page})=>{
 await page.goto('/');await expect(page.locator('canvas')).toBeVisible();const root=makeAtom({title:'Root',x:0,y:0,pinned:true}),leaf=makeAtom({title:'Leaf',x:210,y:0,pinned:true});await importMap(page,{atoms:[root,leaf],links:[makeLink(root.id,leaf.id)]});await page.mouse.move(640,360);await page.mouse.down();await page.mouse.move(650,390,{steps:3});const zone=await page.locator('[data-state="now"]').boundingBox();await page.mouse.move(zone!.x+zone!.width/2,zone!.y+zone!.height/2,{steps:6});await page.mouse.up();await expect(page.locator('.dropzones')).not.toHaveClass(/dropzones-live/);const data=await readMap(page);expect(data.atoms.find(a=>a.id===root.id)?.state).toBe('now');expect(data.atoms.find(a=>a.id===leaf.id)?.state).toBe('normal');
});
test.describe('phone gestures',()=>{test.use({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
 test('hold and trace with one finger selects; release without tracing creates',async({page,context})=>{
  await page.goto('/');await expect(page.locator('canvas')).toBeVisible();await importMap(page,{atoms:[makeAtom({title:'Left',x:-60}),makeAtom({title:'Right',x:60})],links:[]});await enable(page,'Волшебное лассо');const cdp=await context.newCDPSession(page);const touch=(type:string,points:{x:number;y:number;id:number}[])=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points.map(p=>({radiusX:2,radiusY:2,force:1,...p}))});
  await touch('touchStart',[{id:1,x:90,y:290}]);await page.waitForTimeout(600);await expect(page.getByRole('dialog')).toBeHidden();for(const [x,y] of [[90,290],[300,290],[300,540],[90,540],[90,290]]){await touch('touchMove',[{id:1,x,y}]);await page.waitForTimeout(35);}await touch('touchEnd',[]);await expect(page.getByRole('dialog')).toBeHidden();await touch('touchStart',[{id:1,x:135,y:422}]);await page.waitForTimeout(600);await touch('touchMove',[{id:1,x:155,y:442}]);await expect(page.getByRole('dialog')).toBeHidden();await touch('touchEnd',[]);const moved=(await readMap(page)).atoms;expect(moved.find(a=>a.title==='Left')!.x).toBeCloseTo(-40,0);expect(moved.find(a=>a.title==='Right')!.x).toBeCloseTo(80,0);await touch('touchStart',[{id:1,x:155,y:442}]);await page.waitForTimeout(600);await page.locator('canvas').dispatchEvent('contextmenu',{clientX:155,clientY:442});await expect(page.getByRole('dialog')).toBeHidden();await touch('touchEnd',[]);await expect(page.getByRole('dialog',{name:'Действия с атомом'})).toContainText('Выделено: 2');await page.screenshot({animations:'disabled',path:'artifacts/lasso-mobile.png'});await page.getByRole('dialog').getByRole('button',{name:'Закрыть меню атома',exact:true}).click();await touch('touchStart',[{id:1,x:90,y:250}]);await page.waitForTimeout(600);await expect(page.getByRole('dialog')).toBeHidden();await touch('touchEnd',[]);await save(page,'Release creates');expect((await readMap(page)).atoms).toHaveLength(3);
 });
 test('starting a pan on an atom does not move it; a held atom can be moved',async({page,context})=>{
  await page.goto('/');await page.locator('canvas').press('n');await save(page,'Phone');await expect(page.locator('.zoom-controls')).toBeHidden();const cdp=await context.newCDPSession(page);const touch=(type:string,points:{x:number;y:number}[])=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points.map((p,i)=>({id:i+1,radiusX:2,radiusY:2,force:1,...p}))});
  const before=(await readMap(page)).atoms[0];await touch('touchStart',[{x:195,y:422}]);await touch('touchMove',[{x:265,y:470}]);await touch('touchEnd',[]);await expect.poll(async()=>Number(await page.locator('canvas').getAttribute('data-camera-x'))).toBeGreaterThan(40);const after=(await readMap(page)).atoms[0];expect(after.x).toBeCloseTo(before.x,1);expect(after.y).toBeCloseTo(before.y,1);
  await page.reload();await expect(page.locator('canvas')).toHaveAttribute('data-nodes','1');const camera={x:Number(await page.locator('canvas').getAttribute('data-camera-x')),y:Number(await page.locator('canvas').getAttribute('data-camera-y'))};const p={x:195+camera.x,y:422+camera.y};await touch('touchStart',[p]);await page.waitForTimeout(600);await touch('touchMove',[{x:p.x+45,y:p.y+45}]);await touch('touchEnd',[]);await expect.poll(async()=>(await readMap(page)).atoms[0].x).toBeGreaterThan(before.x+30);await page.screenshot({animations:'disabled',path:'artifacts/gesture-ux-mobile.png'});
 });
 test('a second finger switches a prepared hold to pinch without creating or selecting',async({page,context})=>{
  await page.goto('/');await expect(page.locator('canvas')).toBeVisible();await enable(page,'Волшебное лассо');const cdp=await context.newCDPSession(page);const touch=(type:string,points:{x:number;y:number;id:number}[])=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points.map(p=>({radiusX:2,radiusY:2,force:1,...p}))});
  await touch('touchStart',[{id:1,x:80,y:290}]);await page.waitForTimeout(600);await touch('touchStart',[{id:1,x:80,y:290},{id:2,x:300,y:290}]);await page.waitForTimeout(600);await touch('touchMove',[{id:1,x:50,y:290},{id:2,x:330,y:290}]);await touch('touchEnd',[]);await expect.poll(async()=>Number(await page.locator('canvas').getAttribute('data-zoom'))).toBeGreaterThan(1.1);await expect(page.getByRole('dialog')).toBeHidden();await expect(page.locator('footer')).toContainText('0 атомов');
 });
});

test('startup stays neutral while storage is loading',async({page})=>{
 let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);
 await page.route('**/*.wasm',async route=>{await gate;await route.continue();});
 await page.goto('/',{waitUntil:'domcontentloaded'});
 await expect(page.locator('main')).toHaveClass(/booting/);
 const colors=await page.evaluate(()=>[document.body,document.querySelector('#app')!,document.querySelector('main')!].map(el=>getComputedStyle(el).backgroundColor));
 expect(colors).toEqual(['rgb(20, 22, 24)','rgb(20, 22, 24)','rgb(20, 22, 24)']);
 expect(await page.locator('html').getAttribute('data-theme')).toBeNull();
 release();await expect(page.locator('canvas')).toBeVisible();
});
