import {test,expect} from '@playwright/test';
import {readMap} from './helpers';
test.use({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
test('mobile editor fits viewport and supports touch creation',async({page})=>{await page.goto('/');await page.getByRole('button',{name:'+ Первый атом',exact:true}).tap();await page.getByRole('textbox',{name:'Название',exact:true}).fill('Моя первая мысль');await page.getByRole('textbox',{name:'Текст',exact:true}).fill('Записать идею и вернуться к ней завтра.');await page.screenshot({path:'artifacts/mobile-editor.png'});await page.getByRole('button',{name:'Сохранить',exact:true}).tap();await expect(page.getByRole('dialog',{name:'Редактор атома'})).toBeHidden();await expect(page.locator('footer')).toContainText('1 атомов');await expect(page.locator('canvas')).toHaveAttribute('data-nodes','1');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'artifacts/mobile-map.png'});});
test('real touch long press, drag, pan, pinch and state zones are independent',async({page,context})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.getByRole('button',{name:'+ Первый атом',exact:true}).tap();await page.getByRole('textbox',{name:'Название',exact:true}).fill('Touch atom');await page.getByRole('button',{name:'Сохранить',exact:true}).tap();await expect(page.getByRole('dialog',{name:'Редактор атома'})).toBeHidden();await expect(page.locator('canvas')).toHaveAttribute('data-nodes','1');
 await expect(page.getByRole('dialog',{name:'Редактор атома'})).toBeHidden();const cdp=await context.newCDPSession(page);const touch=async(type:'touchStart'|'touchMove'|'touchEnd',points:{x:number;y:number;id?:number}[])=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points.map((p,i)=>({id:p.id??i+1,radiusX:2,radiusY:2,force:1,...p}))});
 await touch('touchStart',[{x:195,y:422}]);await page.waitForTimeout(650);await touch('touchEnd',[]);await expect(page.getByRole('dialog',{name:'Действия с атомом'})).toBeVisible();await expect(page.getByRole('dialog',{name:'Редактор атома'})).toBeHidden();await expect(page.locator('.state-shortcuts').getByRole('button',{name:'Обычный',exact:true})).toBeHidden();await page.getByRole('button',{name:'Закрыть меню атома'}).tap();
 await touch('touchStart',[{x:195,y:422}]);await touch('touchMove',[{x:270,y:480}]);await touch('touchEnd',[]);await page.waitForTimeout(200);const moved=(await readMap(page)).atoms[0];expect(moved.x).toBeCloseTo(75,0);expect(moved.y).toBeCloseTo(58,0);
 await touch('touchStart',[{x:270,y:480}]);await touch('touchMove',[{x:260,y:520}]);await expect(page.locator('[data-state="normal"]')).toBeHidden();const zone=await page.locator('[data-state="now"]').boundingBox();await touch('touchMove',[{x:zone!.x+zone!.width/2,y:zone!.y+zone!.height/2}]);await touch('touchEnd',[]);await page.waitForTimeout(250);let data=await readMap(page);expect(data.atoms[0].state).toBe('now');expect(data.atoms[0].x).toBeCloseTo(moved.x,0);expect(data.atoms[0].y).toBeCloseTo(moved.y,0);
 await page.touchscreen.tap(270,480);await expect(page.getByRole('dialog',{name:'Редактор атома'})).toBeVisible();await page.getByRole('combobox',{name:'Состояние',exact:true}).selectOption('paused');await page.getByRole('button',{name:'Сохранить',exact:true}).tap();await expect(page.getByRole('dialog',{name:'Редактор атома'})).toBeHidden();await page.touchscreen.tap(270,480);await page.getByRole('combobox',{name:'Состояние',exact:true}).selectOption('archived');await page.getByRole('button',{name:'Сохранить',exact:true}).tap();await expect(page.getByRole('dialog',{name:'Редактор атома'})).toBeHidden();
 await page.getByRole('button',{name:'Архив',exact:true}).tap();await expect(page.locator('canvas')).toHaveAttribute('data-nodes','1');await touch('touchStart',[{x:270,y:480}]);await touch('touchMove',[{x:250,y:520}]);await expect(page.locator('.drop')).toHaveCount(1);await expect(page.locator('.drop')).toHaveText('Восстановить');const restore=await page.locator('.drop').boundingBox();await touch('touchMove',[{x:restore!.x+restore!.width/2,y:restore!.y+restore!.height/2}]);await touch('touchEnd',[]);await page.waitForTimeout(200);await page.getByRole('button',{name:'Всё',exact:true}).tap();expect((await readMap(page)).atoms[0].state).toBe('normal');
 await touch('touchStart',[{x:60,y:220}]);await touch('touchMove',[{x:110,y:250}]);await touch('touchEnd',[]);
 await touch('touchStart',[{id:1,x:100,y:300},{id:2,x:240,y:300}]);await touch('touchMove',[{id:1,x:60,y:300},{id:2,x:280,y:300}]);await touch('touchEnd',[]);await expect(page.locator('.zoom-controls span')).not.toHaveText('100%');await expect(page.getByRole('dialog')).toBeHidden();expect(errors).toEqual([]);
});
