import {test,expect,type Page} from '@playwright/test';
async function create(page:Page,title:string){await page.locator('canvas.map').press('n');await page.getByRole('textbox',{name:'Название',exact:true}).fill(title);}
async function save(page:Page){await page.getByRole('button',{name:'Сохранить',exact:true}).click();await expect(page.getByRole('dialog',{name:'Редактор атома'})).toBeHidden();}
async function find(page:Page,title:string){await page.getByRole('button',{name:'Открыть поиск',exact:true}).click();await page.getByRole('textbox',{name:'Поиск',exact:true}).fill(title);await page.locator('.search-results button').filter({hasText:title}).first().click();await expect(page.locator('main')).toHaveAttribute('data-navigation','idle');}
async function settings(page:Page){await page.getByRole('button',{name:'Меню карты',exact:true}).click();await page.getByRole('button',{name:'Настройки и резервные копии',exact:true}).click();}
test('aliases, Markdown sanitization, suggestions, relations, archive, export/import and delete recovery',async({page})=>{
 await page.goto('/');await create(page,'Юрий');await page.getByText('Дополнительно',{exact:true}).click();await page.getByLabel('Алиасы',{exact:true}).fill('Юра, Yury');await save(page);
 await create(page,'Вопросы для Юра');await page.getByRole('textbox',{name:'Текст',exact:true}).fill('## Интервью\n- [ ] Позвонить\n<script>window.hacked=true</script>');await page.getByRole('button',{name:'Просмотр',exact:true}).click();await expect(page.locator('.markdown h2')).toHaveText('Интервью');expect(await page.evaluate(()=>Boolean((window as any).hacked))).toBe(false);await page.getByRole('button',{name:'+ Юрий',exact:false}).click();await save(page);await expect(page.locator('footer')).toContainText('1 связей');
 await page.getByRole('button',{name:'Открыть поиск',exact:true}).click();await page.getByRole('textbox',{name:'Поиск',exact:true}).fill('Yury');await page.locator('.search-results button').filter({hasText:'Юрий'}).click();await expect(page.locator('main')).toHaveAttribute('data-navigation','idle');await page.locator('canvas.map').click({position:{x:640,y:360}});await expect(page.getByRole('textbox',{name:'Название',exact:true})).toHaveValue('Юрий');await page.getByRole('combobox',{name:'Состояние',exact:true}).selectOption('archived');await save(page);await expect(page.locator('footer')).toContainText('1 связей');
 await settings(page);await page.locator('.legacy-backup > summary').click();const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Экспорт карты',exact:true}).click();const download=await downloadPromise;await download.saveAs('artifacts/test-backup.json');await page.getByRole('button',{name:'Закрыть настройки'}).click();
 await find(page,'Юрий');await page.locator('canvas.map').click({position:{x:640,y:360}});await page.getByText('Дополнительно',{exact:true}).click();await page.getByRole('button',{name:'Удалить атом',exact:true}).click();await page.getByRole('button',{name:'Удалить навсегда',exact:true}).click();await expect(page.locator('footer')).toContainText('1 атомов');
 await settings(page);await page.locator('.legacy-backup > summary').click();await page.getByText('Импорт карты',{exact:true}).locator('input').setInputFiles('artifacts/test-backup.json');await page.getByRole('button',{name:'Добавить в карту',exact:true}).click();await expect(page.locator('footer')).toContainText('2 атомов');await expect(page.locator('footer')).toContainText('1 связей');await page.getByRole('button',{name:'Закрыть настройки'}).click();
 await find(page,'Юрий');await page.locator('canvas.map').click({position:{x:640,y:360}});await page.getByText('Связи',{exact:true}).click();await page.getByRole('button',{name:'Удалить связь с Вопросы для Юра',exact:true}).click();await save(page);await expect(page.locator('footer')).toContainText('0 связей');
});
test('community plugin installs with consent, runs and survives offline restart',async({page,context})=>{
 await page.goto('/');await expect(page.locator('canvas.map')).toBeVisible();await settings(page);await page.getByRole('button',{name:'Плагины →',exact:true}).click();await page.getByText('Установить плагин',{exact:true}).click();await page.getByLabel('Пакет плагина',{exact:true}).setInputFiles('artifacts/quick-idea.phosphora');await page.getByRole('button',{name:'Разрешить и установить',exact:true}).click();await expect(page.locator('.plugin-row').filter({hasText:'Быстрая идея'})).toBeVisible({timeout:15000});await expect(page.getByText('Быстрая идея',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Закрыть настройки'}).click();await page.getByRole('button',{name:'Меню карты'}).click();await page.getByRole('button',{name:'Записать новую идею',exact:true}).click();await expect(page.locator('footer')).toContainText('1 атомов');
 await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await context.setOffline(true);await page.reload();await expect(page.locator('canvas.map')).toBeVisible();await page.getByRole('button',{name:'Меню карты'}).click();await page.getByRole('button',{name:'Записать новую идею',exact:true}).click();await expect(page.locator('footer')).toContainText('2 атомов');
});
test('second tab cannot acquire the database and does not reset data',async({page,context})=>{await page.goto('/');await create(page,'Не терять');await save(page);const second=await context.newPage();await second.goto('/');await expect(second.getByRole('alert')).toContainText('другой вкладке');await second.close();await page.reload();await expect(page.locator('footer')).toContainText('1 атомов');});
