import {test,expect} from '@playwright/test';
import {makeAtom} from '../../src/core/model';
import {importMap} from './helpers';
test('body search highlights inflected words in a contextual snippet and saves quietly',async({page})=>{
 await page.goto('/');await expect(page.locator('canvas.map')).toBeVisible();await importMap(page,{atoms:[makeAtom({title:'Планы на выходные',content:'Вступление. '.repeat(25)+'Обсудить с Макаром поездку к морю завтра. '+'Продолжение. '.repeat(25)})],links:[]});
 await page.getByRole('button',{name:'Открыть поиск',exact:true}).click();await expect(page.getByRole('textbox',{name:'Поиск',exact:true})).toBeFocused();await page.getByRole('textbox',{name:'Поиск',exact:true}).fill('Макару поездку');await expect(page.locator('.search-results button')).toHaveCount(1);await expect(page.locator('.search-excerpt')).toContainText('завтра');await expect(page.locator('.search-excerpt mark').first()).toHaveText('Макаром');await expect(page.locator('.search-excerpt mark').last()).toHaveText('поездку');await page.keyboard.press('Escape');
 await page.evaluate(()=>{const button=document.querySelector('.save-status>button')!;const record=()=>({text:button.textContent?.trim(),label:button.getAttribute('aria-label')});(window as any).saveFrames=[record()];new MutationObserver(()=>{(window as any).saveFrames.push(record());}).observe(button,{subtree:true,childList:true,characterData:true,attributes:true});});
 await page.locator('canvas.map').press('n');await page.getByRole('textbox',{name:'Название',exact:true}).fill('Тихое сохранение');await page.getByRole('button',{name:'Сохранить',exact:true}).click();await expect(page.getByRole('dialog',{name:'Редактор атома'})).toBeHidden();await expect(page.getByRole('button',{name:'Сохранение на устройстве',exact:true})).toBeVisible();await expect(page.getByText('Сохранено на устройстве',{exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Сохранение на устройстве',exact:true}).click();await expect(page.locator('.save-popover')).toContainText('Последнее сохранение');
 expect(await page.evaluate(()=>(window as any).saveFrames.every((frame:any)=>frame.text==='✓'&&frame.label==='Сохранение на устройстве'))).toBe(true);
});

test('keyboard search selects any result, resets with new input and returns focus to the map',async({page})=>{
 await page.goto('/');await importMap(page,{atoms:[makeAtom({title:'Journey Alpha',x:-2000,y:0,pinned:true}),makeAtom({title:'Journey Beta',x:2000,y:0,pinned:true}),makeAtom({title:'Journey Gamma',x:0,y:2000,pinned:true})],links:[]});
 await page.keyboard.press('Control+k');const input=page.locator('.search input');await input.fill('Journey');const options=page.getByRole('option');await expect(options).toHaveCount(3);
 await input.press('End');await expect(options.nth(2)).toHaveAttribute('aria-selected','true');await expect(input).toHaveAttribute('aria-activedescendant','search-result-2');
 await input.press('ArrowDown');await expect(options.first()).toHaveAttribute('aria-selected','true');await input.press('ArrowUp');await expect(options.last()).toHaveAttribute('aria-selected','true');
 await input.fill('Journey Beta');await expect(options).toHaveCount(1);await expect(input).toHaveAttribute('aria-activedescendant','search-result-0');await input.press('Enter');await expect(page.locator('.search-results')).toHaveCount(0);await expect(page.locator('canvas.map')).toBeFocused();await expect(page.locator('main')).toHaveAttribute('data-navigation','idle');
 await page.keyboard.press('Control+k');await input.fill('Journey');await input.press('ArrowDown');await expect(options.nth(1)).toHaveAttribute('aria-selected','true');const title=await options.nth(1).locator('span').first().innerText();await input.press('Enter');await expect(page.locator('canvas.map')).toBeFocused();await expect(page.locator('main')).toHaveAttribute('data-navigation','idle');await page.locator('canvas.map').press('Enter');await expect(page.locator('.atom-title')).toHaveValue(title);
});
