import {test,expect} from '@playwright/test';
import {zipSync,strToU8} from 'fflate';
import {openSettings,closeSettings,readMap,importMap} from './helpers';
import {makeAtom} from '../../src/core/model';
test('community structural and physics pair controls actual world layout through public API',async({page})=>{
 await page.goto('/');await expect(page.locator('canvas.map')).toBeVisible();await openSettings(page);await page.getByRole('button',{name:'Плагины →',exact:true}).click();await page.getByText('Установить плагин',{exact:true}).click();const source=`export async function activate(app){await app.graph.registerPhysicsProvider({id:'motion',name:'Static public physics',step:input=>({nodes:input.nodes,energy:0})});await app.graph.registerStructuralProvider({id:'layout',name:'Public structure',description:'Public API acceptance',physicsId:'motion',defaults:{elasticity:.014,repulsion:550,distance:175,damping:.72,inertia:1.8,friction:.8},arrange:({data})=>({positions:data.atoms.map((a,i)=>({id:a.id,x:i*300,y:500})),skeleton:data.links.map(l=>l.id)})});}`;
 await page.getByLabel('Пакет плагина',{exact:true}).setInputFiles({name:'structure.phosphora',mimeType:'application/zip',buffer:Buffer.from(zipSync({'manifest.json':strToU8(JSON.stringify({id:'test.structure',name:'Structure provider',version:'1',apiVersion:1,permissions:['graph']})),'main.js':strToU8(source)}))});await page.getByRole('button',{name:'Разрешить и установить',exact:true}).click();await expect(page.locator('.plugin-row').filter({hasText:'Structure provider'})).toBeVisible();await closeSettings(page);
 await openSettings(page);await page.getByRole('button',{name:'Public structure',exact:true}).click();await closeSettings(page);const atoms=Array.from({length:10},(_,i)=>makeAtom({id:'public-'+i,title:'Public '+i}));await importMap(page,{atoms,links:[]});await expect(page.locator('canvas.map')).toHaveAttribute('data-layout','idle');const map=await readMap(page);expect(map.atoms.map(a=>a.y)).toEqual(Array(10).fill(500));expect(new Set(map.atoms.map(a=>a.x)).size).toBe(10);await page.reload();await expect(page.locator('canvas.map')).toHaveAttribute('data-layout','idle');expect((await readMap(page)).atoms.map(a=>a.y)).toEqual(Array(10).fill(500));
});
