import {test,expect,type Page} from '@playwright/test';
import {openSettings,closeSettings,focus,importMap} from './helpers';
import {makeAtom} from '../../src/core/model';
async function checkText(page:Page){const bad=await page.evaluate(()=>{const rgb=(s:string)=>{const m=s.match(/[\d.]+/g);return m?m.slice(0,3).map(Number):[0,0,0];};const lum=(c:number[])=>c.map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;}).reduce((sum,v,i)=>sum+v*[.2126,.7152,.0722][i],0);const result:string[]=[];for(const el of document.querySelectorAll<HTMLElement>('button,p,small,summary,strong,input:not([type=color]):not([type=range])')){const s=getComputedStyle(el);if(!el.getClientRects().length||s.visibility==='hidden'||Number(s.opacity)<1||el.matches(':disabled')||el.closest('.swatches')||(!el.textContent?.trim()&&!el.matches('input')))continue;let parent:HTMLElement|null=el,bg='';while(parent){const color=getComputedStyle(parent).backgroundColor;if(color!=='rgba(0, 0, 0, 0)'&&color!=='transparent'){bg=color;break;}parent=parent.parentElement;}if(!bg)continue;const a=lum(rgb(s.color)),b=lum(rgb(bg));const ratio=(Math.max(a,b)+.05)/(Math.min(a,b)+.05);if(ratio<4.45)result.push(`${el.tagName}.${el.className} ${el.textContent?.trim().slice(0,35)} ${s.color}/${bg} = ${ratio.toFixed(2)}`);}return result;});expect(bad).toEqual([]);}
test('semantic colors cover settings, map controls, cards and confirmation in dark and light themes',async({page})=>{
 test.setTimeout(90000);await page.goto('/');await expect(page.locator('canvas.map')).toBeVisible();await importMap(page,{atoms:[makeAtom({title:'A quiet thought',content:'A place to collect ideas.',pinned:true})],links:[]});
 for(const name of ['Светлая','Тёмная','Ромашки','Звёздная ночь']){await openSettings(page);await page.getByRole('button',{name,exact:true}).click();await checkText(page);await closeSettings(page);await focus(page,'A quiet thought');await checkText(page);await page.getByText('Дополнительно',{exact:true}).click();await page.getByRole('button',{name:'Удалить атом',exact:true}).click();await checkText(page);await page.getByRole('button',{name:'Отмена',exact:true}).click();await page.getByRole('button',{name:'Закрыть редактор',exact:true}).click();await page.screenshot({animations:'disabled',path:`artifacts/theme-${name==='Ромашки'?'daisies':name==='Светлая'?'light':name==='Тёмная'?'dark':'stars'}.png`});}
});
test('visual theme editor previews, cancels, saves, exports and persists colors and decoration offline',async({page,context})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');await expect(page.locator('canvas.map')).toBeVisible();await openSettings(page);const original=await page.locator('html').evaluate(el=>(el as HTMLElement).style.getPropertyValue('--theme-background'));await page.getByRole('button',{name:'Настроить тему',exact:true}).click();await page.getByLabel('Цвет темы: Фон',{exact:true}).fill('#777777');await page.getByLabel('Цвет темы: Акцент',{exact:true}).fill('#ffff00');await page.getByLabel('Рисунок фона',{exact:true}).selectOption('daisies');await page.getByLabel('Зернистость',{exact:true}).fill('0.65');await expect(page.locator('html')).toHaveAttribute('data-pattern','daisies');await checkText(page);await page.getByRole('button',{name:'Отменить редактирование темы',exact:true}).click();expect(await page.locator('html').evaluate(el=>(el as HTMLElement).style.getPropertyValue('--theme-background'))).toBe(original);
 await page.getByRole('button',{name:'Настроить тему',exact:true}).click();await page.getByLabel('Название темы',{exact:true}).fill('Мои светлячки');await page.getByLabel('Цвет темы: Фон',{exact:true}).fill('#102023');await page.getByLabel('Цвет темы: Акцент',{exact:true}).fill('#fae7a0');await page.getByLabel('Цвет темы: Оттенок',{exact:true}).fill('#458c73');await page.getByLabel('Рисунок фона',{exact:true}).selectOption('fireflies');await page.getByLabel('Зернистость',{exact:true}).fill('0.5');await page.locator('.theme-designer').scrollIntoViewIfNeeded();await page.screenshot({animations:'disabled',path:'artifacts/theme-editor-mobile.png'});await page.getByRole('button',{name:'Сохранить тему',exact:true}).click();await expect(page.getByRole('button',{name:'Мои светлячки',exact:true})).toBeVisible();
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Экспорт темы',exact:true}).click();const stream=await(await pending).createReadStream();let text='';for await(const chunk of stream!)text+=chunk.toString();const file=JSON.parse(text);expect(file.version).toBe(2);expect(file.theme.base.background).toBe('#102023');expect(file.theme.effects).toMatchObject({pattern:'fireflies',grain:.5});await closeSettings(page);await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await context.setOffline(true);await page.reload();await expect(page.locator('canvas.map')).toBeVisible();await expect(page.locator('html')).toHaveAttribute('data-theme',file.theme.id);await expect(page.locator('html')).toHaveAttribute('data-pattern','fireflies');expect(await page.locator('html').evaluate(el=>(el as HTMLElement).style.getPropertyValue('--theme-grain-image'))).toContain('feTurbulence');await page.screenshot({animations:'disabled',path:'artifacts/theme-fireflies-mobile.png'});
});
