import {test,expect} from '@playwright/test';
import {openSettings,closeSettings,readMap} from './helpers';
async function create(page:any,title:string){await page.getByRole('button',{name:'+ Создать',exact:true}).click();await page.getByRole('textbox',{name:'Название',exact:true}).fill(title);await page.getByRole('button',{name:'Сохранить',exact:true}).click();await expect(page.getByRole('dialog',{name:'Редактор атома'})).toBeHidden();}
test('independent SQLite workspaces preserve notes and themes across switches, renames and offline restart',async({page,context})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.locator('canvas')).toBeVisible();await create(page,'Only in Main');
 await page.getByRole('button',{name:'Выбрать хранилище'}).click();await page.getByRole('button',{name:'Новое хранилище',exact:true}).click();await page.getByRole('textbox',{name:'Название хранилища',exact:true}).fill('Работа');await page.getByRole('button',{name:'Создать и открыть',exact:true}).click();await expect(page.locator('.workspace-switch')).toContainText('Работа');await expect(page.locator('footer')).toContainText('0 атомов');await create(page,'Only in Work');await openSettings(page);await page.getByRole('button',{name:'Неон',exact:true}).click();await closeSettings(page);
 await page.getByRole('button',{name:'Выбрать хранилище'}).click();await page.getByRole('button',{name:'Переименовать текущее'}).click();await page.getByRole('textbox',{name:'Название хранилища',exact:true}).fill('Студия');await page.getByRole('button',{name:'Сохранить название'}).click();await page.getByRole('button',{name:'Закрыть хранилища'}).click();await expect(page.locator('.workspace-switch')).toContainText('Студия');
 await page.getByRole('button',{name:'Выбрать хранилище'}).click();await page.locator('.workspace-list button').filter({hasText:'Основное'}).click();await expect(page.locator('.workspace-switch')).toContainText('Основное');expect((await readMap(page)).atoms.map(a=>a.title)).toEqual(['Only in Main']);await expect(page.locator('html')).toHaveAttribute('data-theme','phosphor');
 await page.getByRole('button',{name:'Выбрать хранилище'}).click();await page.locator('.workspace-list button').filter({hasText:'Студия'}).click();await expect(page.locator('.workspace-switch')).toContainText('Студия');expect((await readMap(page)).atoms.map(a=>a.title)).toEqual(['Only in Work']);await expect(page.locator('html')).toHaveAttribute('data-theme','neon');await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await context.setOffline(true);await page.reload();await expect(page.locator('.workspace-switch')).toContainText('Студия');await expect(page.locator('footer')).toContainText('1 атомов');await page.getByRole('button',{name:'Выбрать хранилище'}).click();await page.screenshot({animations:'disabled',path:'artifacts/workspaces-desktop.png'});await page.setViewportSize({width:390,height:844});await page.screenshot({animations:'disabled',path:'artifacts/workspaces-mobile.png'});await page.locator('.workspace-list button').filter({hasText:'Основное'}).click();await expect(page.locator('.workspace-switch')).toContainText('Основное');expect((await readMap(page)).atoms[0].title).toBe('Only in Main');expect(errors).toEqual([]);
});
