import {test,expect} from '@playwright/test';
import {zipSync,strToU8,unzipSync} from 'fflate';
import {openSettings,closeSettings,focus,readMap} from './helpers';
test('vault import, fullscreen writing, wiki navigation, attachments, theme persistence and export',async({page})=>{
 await page.goto('/');await expect(page.locator('canvas')).toBeVisible();await openSettings(page);
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aL1sAAAAASUVORK5CYII=','base64');
 const source={'People/Alice.md':strToU8('---\naliases: [Al]\nunknown: 001 # keep\n---\nHello **world**\n[[../Projects/Book|Book]]\n![[../images/pixel.png]]'),'Projects/Book.md':strToU8('# Book\n'),'images/pixel.png':png,'.obsidian/app.json':strToU8('{"test":1}')};
 await page.getByLabel('ZIP Obsidian').setInputFiles({name:'Vault.zip',mimeType:'application/zip',buffer:Buffer.from(zipSync(source))});await page.getByRole('button',{name:'Импортировать хранилище',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Все 4 файлов'})).toBeVisible();
 await page.getByRole('button',{name:'Светлая',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('data-color-mode','light');await closeSettings(page);await page.reload();await expect(page.locator('canvas')).toBeVisible();await expect(page.locator('html')).toHaveAttribute('data-color-mode','light');
 await focus(page,'Alice');await expect(page.locator('.markdown strong')).toHaveText('world');await expect(page.locator('.markdown img')).toBeVisible();await expect(page.locator('.markdown img')).toHaveJSProperty('naturalWidth',1);
 await page.locator('.markdown a[data-atom]').click();await expect(page.getByRole('textbox',{name:'Название',exact:true})).toHaveValue('Book');await page.getByRole('button',{name:'Закрыть редактор',exact:true}).click();await focus(page,'Alice');
 await page.getByRole('button',{name:'Развернуть редактор',exact:true}).click();await expect(page.locator('.note-editor')).toHaveClass(/expanded/);await page.getByRole('button',{name:'Редактировать',exact:true}).click();const text=page.getByRole('textbox',{name:'Текст',exact:true});await text.fill('A new paragraph');await text.evaluate((el:HTMLTextAreaElement)=>{el.setSelectionRange(2,5);el.dispatchEvent(new Event('select'));});await page.getByRole('button',{name:'Жирный',exact:true}).click();await expect(text).toHaveValue('A **new** paragraph');await text.press('End');await page.getByRole('button',{name:'↗ Связать',exact:true}).click();await page.getByRole('textbox',{name:'Быстрая связь'}).fill('Book');await page.locator('.quick-link-picker button').click();await expect(text).toHaveValue(/\[\[Projects\/Book\|Book\]\]/);await expect(page.getByLabel('Тип',{exact:true})).toBeVisible();await expect(page.getByRole('textbox',{name:/JSON/})).toHaveCount(0);
 await page.screenshot({path:'artifacts/fullscreen-light-desktop.png'});await page.getByRole('button',{name:'Сохранить',exact:true}).click();await openSettings(page);const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Экспорт Markdown',exact:true}).click();const stream=await(await pending).createReadStream();const chunks:Buffer[]=[];for await(const c of stream!)chunks.push(c as Buffer);const result=unzipSync(Buffer.concat(chunks));expect(result['images/pixel.png']).toEqual(new Uint8Array(png));expect(result['.obsidian/app.json']).toEqual(source['.obsidian/app.json']);expect(new TextDecoder().decode(result['People/Alice.md'])).toContain('unknown: 001 # keep');expect(new TextDecoder().decode(result['People/Alice.md'])).toContain('**new**');
});
test('mobile fullscreen remains within viewport and custom themes import',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');await expect(page.locator('canvas')).toBeVisible();await page.locator('canvas').press('n');await page.getByRole('button',{name:'Развернуть редактор'}).click();await page.getByRole('textbox',{name:'Название',exact:true}).fill('Mobile');await page.getByRole('textbox',{name:'Текст',exact:true}).fill('A long note\n'.repeat(80));const bounds=await page.locator('.note-editor').boundingBox();expect(bounds!.width).toBeLessThanOrEqual(390);await page.getByRole('button',{name:'Сохранить',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/fullscreen-mobile.png'});await page.getByRole('button',{name:'Сохранить',exact:true}).click();await openSettings(page);
 const {THEMES,themeFile}=await import('../../src/core/themes');const theme={...THEMES[0],id:'my-theme',name:'Моя тема'};await page.getByLabel('Импорт темы',{exact:true}).setInputFiles({name:'custom.phosphored-theme',mimeType:'application/json',buffer:Buffer.from(themeFile(theme))});await expect(page.locator('html')).toHaveAttribute('data-theme','custom-my-theme');await page.reload();await expect(page.locator('html')).toHaveAttribute('data-theme','custom-my-theme');
});
