import {activeNeighborhood} from './activity';
import {dragWeights} from './drag-response';
import {semanticLevel} from './semantic';
import {collapseAmount,topologyKey} from './lod';
import {structure} from './structure';
import {footprint} from './footprint';
import type {Snapshot,PositionUpdate} from '../core/model';
import type {Preferences} from '../core/preferences';
import type {GraphProviders,StructuralProvider} from './providers';
import type {GraphModel,Camera} from './model';
import {dropResistance,type Body,type PhysicsInput} from './physics';
export class GraphController {
 private dragNeighbors=new Map<string,{x:number;y:number;resistance:number}>();private dragWeights=new Map<string,number>();private previousDrag={x:0,y:0};
 private layoutVersion=0;private arranging=false;private structuralProvider?:StructuralProvider;
 private membership=new Map<string,{component:string;branch:string}>();private restLengths=new Map<string,number>();private topology='';private skeleton=new Set<string>();private motionVersion=0;private dragOrigins=new Map<string,{x:number;y:number;resistance:number}>();private dragCenter={x:0,y:0};
 private bodies=new Map<string,Body>();private snapshot:Snapshot={atoms:[],links:[]};private model:GraphModel={nodes:[],links:[],hidden:0};private signature='';private projectId=0;private timer:ReturnType<typeof setTimeout>|undefined;private disposed=false;private active=false;private busy=false;private quiet=0;private paused=false;private dirty=new Set<string>();private persistBusy=false;private persistedAt=0;private edited=new Set<string>();private dragged?:{id:string;x:number;y:number;resistance:number};
  private prefs!:Preferences;private camera:Camera={x:0,y:0,zoom:1};private width=1200;private height=800;private lens='all';private selected='';private reduced=false;private collapsed=false;private cloned?:Snapshot;private clonedFor='';private branch:string[]=[];private branchKey='';private interacting=false;
 private shown?:import('./model').GraphModel;private projectPending=false;
 constructor(private providers:GraphProviders,private render:(model:GraphModel)=>void,private persist:(positions:PositionUpdate[],manual:boolean)=>Promise<void>,private error:(e:Error)=>void){}
 sync(data:Snapshot,prefs:Preferences,providerVersion:number){const provider=this.providers.structural(prefs.graphModel);const modeChanged=Boolean(this.prefs&&(this.prefs.preset!==prefs.preset||this.prefs.graphModel!==prefs.graphModel||this.prefs.physics.distance!==prefs.physics.distance||this.structuralProvider!==provider));this.structuralProvider=provider;const previous=new Map(this.snapshot.atoms.map(a=>[a.id,a]));const oldLinks=new Map(this.snapshot.links.map(l=>[l.id,l]));const newLinks=new Map(data.links.map(l=>[l.id,l]));for(const l of [...this.snapshot.links,...data.links]){const old=oldLinks.get(l.id),next=newLinks.get(l.id);if(!old||!next||old.relation!==next.relation){this.edited.add(l.from);this.edited.add(l.to);}}this.snapshot=data;this.prefs=prefs;const signature=JSON.stringify([data.atoms.map(a=>[a.id,a.revision,a.pinned,a.appearance,a.importance]),data.links.map(l=>[l.id,l.relation]),[prefs.physics,prefs.preset,prefs.pinning,prefs.graphModel],providerVersion]);const changed=signature!==this.signature;this.signature=signature;const ids=new Set(data.atoms.map(a=>a.id));for(const id of this.bodies.keys())if(!ids.has(id)){this.bodies.delete(id);this.dirty.delete(id);}
 for(const a of data.atoms){const b=this.bodies.get(a.id);if(!b){this.bodies.set(a.id,{id:a.id,x:a.x,y:a.y,vx:0,vy:0,radius:a.appearance.size_override||30,mass:1+a.importance*.3,pinned:a.pinned,resistance:a.spatial.resistance});if(previous.size&&this.edited.size<100)this.edited.add(a.id);}else if(b.pinned!==a.pinned){b.pinned=a.pinned;b.resistance=0;b.vx=b.vy=0;this.edited.add(a.id);}if(b){b.mass=1+a.importance*.3;const prior=previous.get(a.id);if(prior&&prior.revision!==a.revision)this.edited.add(a.id);if(prior&&prior.revision!==a.revision&&(prior.x!==a.x||prior.y!==a.y)){b.x=a.x;b.y=a.y;b.vx=b.vy=0;b.resistance=a.spatial.resistance;this.dirty.delete(a.id);}}}
 const topology=JSON.stringify([data.atoms.map(a=>a.id).sort(),data.links.map(l=>l.id).sort()]);if(topology!==this.topology||modeChanged){const first=!this.topology,significant=!first&&Math.abs(data.atoms.length-previous.size)>5&&Math.abs(data.atoms.length-previous.size)>previous.size*.15;this.topology=topology;const tree=structure(data);this.membership.clear();for(const root of tree.roots){this.membership.set(root,{component:root,branch:root});for(const branch of tree.children.get(root)||[])for(const id of tree.descendants(branch))this.membership.set(id,{component:root,branch});}for(const l of data.links){if(!oldLinks.has(l.id)&&previous.has(l.from)&&previous.has(l.to))for(const id of [l.from,l.to]){const b=this.bodies.get(id);if(b&&!b.pinned)b.resistance=Math.min(b.resistance,prefs.physics.friction*2);}}if(first||significant||modeChanged)void this.arrange(data,previous,first,significant,modeChanged,signature);else{this.layoutVersion++;this.arranging=false;this.skeleton=structure(data).edges;for(const l of data.links)if(!this.restLengths.has(l.id)){const a=this.bodies.get(l.from),b=this.bodies.get(l.to);if(a&&b&&data.atoms.length>5)this.restLengths.set(l.id,Math.hypot(a.x-b.x,a.y-b.y));}} }

 if(changed){this.signature=signature;this.project();this.wake();}}
 private async arrange(data:Snapshot,previous:Map<string,Snapshot['atoms'][number]>,first:boolean,significant:boolean,modeChanged:boolean,signature:string){const version=++this.layoutVersion,motion=this.motionVersion;this.arranging=true;this.paint();try{const locked=new Set(data.atoms.filter(a=>a.pinned||(!modeChanged&&Boolean((a.properties.obsidian as Record<string,unknown>|undefined)?.phosphored_position))).map(a=>a.id));const provider=this.structuralProvider;const result=provider?await provider.arrange({data:structuredClone(data),settings:{...this.prefs.physics},intent:first?'resume':'reflow',locked:[...locked]}):{positions:data.atoms.map(a=>({id:a.id,x:a.x,y:a.y})),skeleton:[...structure(data).edges]};if(version!==this.layoutVersion||motion!==this.motionVersion||this.disposed)return;if(signature!==this.signature){void this.arrange(this.snapshot,previous,first,significant,modeChanged,this.signature);return;}
 const ids=new Set(data.atoms.map(a=>a.id)),linkIds=new Set(data.links.map(l=>l.id));if(!result||!Array.isArray(result.positions)||result.positions.length!==ids.size||new Set(result.positions.map(p=>p.id)).size!==ids.size||result.positions.some(p=>!ids.has(p.id)||!Number.isFinite(p.x)||!Number.isFinite(p.y)||Math.abs(p.x)>1e7||Math.abs(p.y)>1e7)||!Array.isArray(result.skeleton)||result.skeleton.some(id=>!linkIds.has(id)))throw Error('Invalid structural provider result');const points=new Map(result.positions.map(p=>[p.id,p]));for(const a of data.atoms)if(locked.has(a.id)&&(points.get(a.id)!.x!==a.x||points.get(a.id)!.y!==a.y))throw Error('Structural provider moved a locked atom');this.skeleton=new Set(result.skeleton);
 for(const l of data.links){if(data.atoms.length<=5)this.restLengths.delete(l.id);const a=first?this.bodies.get(l.from):points.get(l.from),b=first?this.bodies.get(l.to):points.get(l.to);if(a&&b&&data.atoms.length>5&&(modeChanged||!this.restLengths.has(l.id)))this.restLengths.set(l.id,Math.hypot(a.x-b.x,a.y-b.y));}
 for(const a of data.atoms){const b=this.bodies.get(a.id)!;if(!b||a.pinned)continue;const importedPosition=Boolean((a.properties.obsidian as Record<string,unknown>|undefined)?.phosphored_position);if((significant&&!importedPosition||modeChanged)&&data.atoms.length>5){const target=points.get(a.id)!;b.target={x:target.x,y:target.y};if(modeChanged){b.resistance=Math.min(b.resistance,this.prefs.physics.friction*2);}this.edited.add(a.id);}else b.target=undefined;}this.project();
 }catch(e){if(version===this.layoutVersion&&!this.disposed)this.error(e as Error);}finally{if(version===this.layoutVersion){this.arranging=false;this.paint();this.wake();}}}
 view(camera:Camera,width:number,height:number,lens:string,selected:string,paused:boolean,reduced:boolean){const collapsed=semanticLevel(camera.zoom,this.collapsed);const project=lens!==this.lens||selected!==this.selected;this.collapsed=collapsed;const resumed=this.paused&&!paused;this.camera={...camera};this.width=width;this.height=height;this.lens=lens;this.selected=selected;this.paused=paused;this.reduced=reduced;if(project)this.project();if(resumed)this.wake();if(paused)this.flush();}
  private async project(){if(this.interacting){this.projectPending=true;return;}const id=++this.projectId;try{
  // The projection inputs only change with the snapshot. Crossing a level boundary
  // reuses the last stable copy rather than rebuilding the world.
  if(this.clonedFor!==this.signature){this.cloned=structuredClone(this.snapshot);this.clonedFor=this.signature;this.branchKey='';}
  const original=this.cloned!;const reduced=await this.providers.active(this.providers.reduction).reduce({data:original,selected:this.selected});const known=new Map(original.links.map(l=>[l.id,l]));if(!Array.isArray(reduced)||reduced.some(l=>!known.has(l.id)))throw Error('Провайдер связей вернул неизвестные данные.');const data={...original,links:reduced.map(l=>known.get(l.id)!)};const [model,expanded,weights]=await Promise.all([this.providers.active(this.providers.clustering).project({data:original,lens:this.providers.hasTool('ambient-lens')&&this.lens!=='all'?'ambient':this.lens,zoom:.3,selected:this.selected}),this.providers.active(this.providers.clustering).project({data:original,lens:this.providers.hasTool('ambient-lens')&&this.lens!=='all'?'ambient':this.lens,zoom:1,selected:this.selected}),this.providers.active(this.providers.weight).weigh(original)]);if(id!==this.projectId||this.disposed)return;if(this.interacting){this.projectPending=true;return;}if(!model||!Array.isArray(model.nodes)||!Array.isArray(model.links))throw Error('Некорректная проекция карты.');for(const a of original.atoms){const b=this.bodies.get(a.id),weight=weights[a.id];if(b&&weight!==undefined){if(!Number.isFinite(weight))throw Error("Invalid node weight");const shape=a.appearance.shape||(a.type==="task"?"square":"circle");const radius=Math.max(18,Math.min(64,weight))*(shape==="diamond"?1.2:shape==="square"?Math.SQRT2:1);if(b.radius!==radius)this.edited.add(a.id);b.radius=radius;Object.assign(b,footprint(a.title,radius,Boolean(a.content)));}}for(const n of [...model.nodes,...expanded.nodes]){if(!Number.isFinite(n.x)||!Number.isFinite(n.y))throw Error('Некорректная позиция кластера.');const radius=weights[n.id];if(radius!==undefined){if(!Number.isFinite(radius))throw Error('Некорректный вес атома.');n.radius=Math.max(18,Math.min(64,radius));const b=this.bodies.get(n.id);if(b)b.radius=n.radius*(n.shape==='diamond'?1.2:n.shape==='square'?Math.SQRT2:1);}}
  const branch=this.branchFor(original);const reducedIds=new Set(reduced.map(l=>l.id));const shownLinks=model.links.filter(l=>reducedIds.has(l.id));this.model={...model,expanded:{...expanded,links:expanded.links.filter(l=>reducedIds.has(l.id))},links:shownLinks,branch,hidden:original.links.length-shownLinks.length};this.paint();}catch(e){if(!this.disposed)this.error(e as Error);}}
  /** Members of the focused branch, so the map can light its skeleton without a frame. */
  private branchFor(data:Snapshot):string[]{if(!this.selected)return[];const key=this.selected+':'+topologyKey(data);if(this.branchKey===key)return this.branch;this.branchKey=key;this.branch=structure(data).descendants(this.selected);return this.branch;}
 private paint(){const position=(n:import('./model').GraphNode)=>{const b=this.bodies.get(n.id);if(b)return{...n,x:b.x,y:b.y};if(n.members){const members=n.members.map(id=>this.bodies.get(id)).filter((b):b is Body=>Boolean(b));if(members.length)return{...n,x:members.reduce((s,b)=>s+b.x,0)/members.length,y:members.reduce((s,b)=>s+b.y,0)/members.length};}return n;};const nodes=this.model.nodes.map(position);const expanded=this.model.expanded?{...this.model.expanded,nodes:this.model.expanded.nodes.map(position)}:undefined;const grouped=new Set(this.model.nodes.flatMap(n=>n.members||[]));const satellites=this.snapshot.atoms.filter(a=>grouped.has(a.id)).map(a=>({id:a.id,x:this.bodies.get(a.id)?.x??a.x,y:this.bodies.get(a.id)?.y??a.y,color:a.appearance.color||'#b4ecc1'}));this.shown={...this.model,expanded,nodes,satellites,arranging:this.arranging};this.render(this.shown);}
 /** A drag moves a few bodies, but a hand sends pointer events far faster than
  *  frames arrive. Rebuilding the whole projection per event is what made a drag
  *  feel like it was fighting the pointer, so during one only the coordinates that
  *  actually changed are written, in place, into the projection the renderer is
  *  already showing, with nothing reallocated and no reactive rebuild. */
 private repaintPositions(){const shown=this.shown||this.model;const place=(n:import('./model').GraphNode)=>{const b=this.bodies.get(n.id);if(b){n.x=b.x;n.y=b.y;return;}if(n.members){let sum=0,count=0;for(const id of n.members){const member=this.bodies.get(id);if(member){sum+=member.x;count++;}}if(count){n.x=sum/count;n.y=sum/count;}}};
  for(const n of shown.nodes)place(n);
  if(shown.expanded)for(const n of shown.expanded.nodes)place(n);
  for(const s of shown.satellites||[]){const b=this.bodies.get(s.id);if(b){s.x=b.x;s.y=b.y;}}}
 private input():PhysicsInput {const activeIds=activeNeighborhood(this.snapshot,this.bodies,[...this.dragOrigins.keys(),...this.edited]);const all=new Set(activeIds);for(const l of this.snapshot.links){if(activeIds.has(l.from))all.add(l.to);if(activeIds.has(l.to))all.add(l.from);}const allowed=new Set([...all].slice(0,800));const nodes=[...allowed].map(id=>this.bodies.get(id)).filter((b):b is Body=>Boolean(b)).map(b=>({...b,...this.membership.get(b.id),boundary:!activeIds.has(b.id),dragged:this.dragOrigins.has(b.id)}));return{nodes,links:this.snapshot.links.filter(l=>allowed.has(l.from)&&allowed.has(l.to)).map(l=>({from:l.from,to:l.to,strength:this.skeleton.has(l.id)?1:.04,distance:Math.max(this.prefs.physics.distance,(this.bodies.get(l.from)?.halfWidth||35)+(this.bodies.get(l.to)?.halfWidth||35)+35)*(this.membership.get(l.from)?.branch!==this.membership.get(l.to)?.branch?1.35:1)})),settings:this.prefs.physics,mode:this.prefs.preset,dt:1,reducedMotion:this.reduced};}
 private wake(){if(this.disposed||!this.prefs)return;this.active=true;this.quiet=0;if(!this.timer)this.timer=setTimeout(()=>this.tick(),16);}
 private async tick(){this.timer=undefined;if(this.disposed||this.busy||this.arranging)return;if(this.paused||document.hidden){this.active=false;this.flush();return;}
  // Pointer, wheel, camera, hit testing and drag always outrank the simulation.
  // A gesture in flight stops the background step outright, and the last stable
  // world state stays on screen rather than a half computed one.
  if(this.interacting)return;
  this.busy=true;try{const input=this.input();if(!input.nodes.length){this.active=false;return;}const version=this.motionVersion,signature=this.signature;const result=await this.providers.motion(this.prefs.graphModel).step(input);if(this.disposed||version!==this.motionVersion||signature!==this.signature)return;if(!result||!Array.isArray(result.nodes))throw Error('Physics provider вернул некорректный кадр.');let energy=0;const originals=new Map(input.nodes.map(n=>[n.id,n]));for(const n of result.nodes){const old=originals.get(n.id),b=this.bodies.get(n.id);if(!old||!b||b.pinned||old.boundary||this.dragOrigins.has(b.id))continue;if(![n.x,n.y,n.vx,n.vy,n.resistance].every(Number.isFinite))throw Error('Physics provider вернул нечисловое значение.');const dx=n.x-b.x,dy=n.y-b.y;const d=Math.hypot(dx,dy);const limit=12;const ratio=d>limit?limit/d:1;b.x+=dx*ratio;b.y+=dy*ratio;b.vx=n.vx;b.vy=n.vy;b.resistance=Math.max(0,Math.min(10000,n.resistance));if(d>.000001)this.dirty.add(b.id);energy+=d;}
 this.paint();if(energy<.001)this.quiet++;else this.quiet=0;if(Date.now()-this.persistedAt>180)this.flush();if(this.quiet>12&&!this.dragged){this.active=false;this.edited.clear();this.flush();}
 }catch(e){this.active=false;if(!this.disposed)this.error(e as Error);}finally{this.busy=false;if(this.active&&!this.disposed)this.timer=setTimeout(()=>this.tick(),32);}}
  beginDrag(id:string,members?:string[]){this.dragNeighbors.clear();this.motionVersion++;const ids=members||[id];this.dragOrigins.clear();for(const key of ids){const b=this.bodies.get(key);if(!b)continue;this.dragOrigins.set(key,{x:b.x,y:b.y,resistance:b.resistance});b.vx=b.vy=0;b.target=undefined;this.edited.add(key);}if(!this.dragOrigins.size)return;const values=[...this.dragOrigins.values()];this.dragCenter={x:values.reduce((sum,p)=>sum+p.x,0)/values.length,y:values.reduce((sum,p)=>sum+p.y,0)/values.length};this.dragged={id,...this.dragCenter,resistance:0}; this.previousDrag={...this.dragCenter};this.dragWeights=dragWeights(this.snapshot,[...this.dragOrigins.keys()]);this.wake();}
  drag(id:string,x:number,y:number){if(this.dragged?.id!==id)return;const dx=x-this.previousDrag.x,dy=y-this.previousDrag.y;this.previousDrag={x,y};for(const [key,weight] of this.dragWeights){const b=this.bodies.get(key);if(!b||b.pinned||this.dragOrigins.has(key))continue;if(!this.dragNeighbors.has(key))this.dragNeighbors.set(key,{x:b.x,y:b.y,resistance:b.resistance});b.target=undefined;const scale=weight/(1+b.resistance*.3);b.x+=dx*scale;b.y+=dy*scale;b.vx=b.vy=0;this.dirty.add(key);this.edited.add(key);}for(const [key,origin] of this.dragOrigins){const b=this.bodies.get(key)!;b.x=origin.x+x-this.dragCenter.x;b.y=origin.y+y-this.dragCenter.y;b.vx=b.vy=0;} this.repaintPositions();this.wake();}
 async endDrag(stateDrop:boolean){this.motionVersion++;if(!this.dragged)return;const input=this.input(),positions:PositionUpdate[]=[];for(const [id,origin] of this.dragOrigins){const b=this.bodies.get(id)!;if(stateDrop){b.x=origin.x;b.y=origin.y;b.resistance=origin.resistance;}else b.resistance=dropResistance(input,id);b.vx=b.vy=0;this.dirty.delete(id);positions.push({id,x:b.x,y:b.y,resistance:b.resistance});}if(stateDrop)for(const [id,origin] of this.dragNeighbors){const b=this.bodies.get(id);if(b){Object.assign(b,origin,{vx:0,vy:0});positions.push({id,...origin});this.dirty.delete(id);}}this.dragNeighbors.clear();this.dragged=undefined;this.dragOrigins.clear();await this.persist(positions,true);this.paint();this.wake();}
 cancelDrag(){this.motionVersion++;for(const [id,origin] of this.dragNeighbors){const b=this.bodies.get(id);if(b){Object.assign(b,origin,{vx:0,vy:0});this.dirty.add(id);}}this.dragNeighbors.clear();for(const [id,origin] of this.dragOrigins){const b=this.bodies.get(id);if(b)Object.assign(b,origin,{vx:0,vy:0});}this.dragOrigins.clear();this.dragged=undefined;this.paint();}
 async flush(){if(this.interacting||this.persistBusy||!this.dirty.size||this.disposed)return;const ids=[...this.dirty].filter(id=>!this.dragOrigins.has(id)&&!this.dragNeighbors.has(id));if(!ids.length)return;const positions=ids.map(id=>this.bodies.get(id)).filter((b):b is Body=>Boolean(b)).map(b=>({id:b.id,x:b.x,y:b.y,resistance:b.resistance}));ids.forEach(id=>this.dirty.delete(id));this.persistBusy=true;try{await this.persist(positions,false);this.persistedAt=Date.now();}catch(e){ids.forEach(id=>this.dirty.add(id));this.active=false;this.error(e as Error);}finally{this.persistBusy=false;}}
 close(){this.disposed=true;clearTimeout(this.timer);this.projectId++;this.layoutVersion++;}
  setInteracting(active:boolean){if(active===this.interacting)return;this.interacting=active;if(active){this.motionVersion++;clearTimeout(this.timer);this.timer=undefined;}else{if(this.projectPending){this.projectPending=false;void this.project();}this.wake();}}
}
