<script lang="ts">
 import SelectionOptions from './SelectionOptions.svelte';
 import {surface} from './surfaces';
 import {onMount} from 'svelte';
 import type {Atom,AtomState} from '../core/model';
 let {destinationOnly=false,ids,pinned,atoms,onpatch,onmove,onaction,onclose}:{destinationOnly?:boolean;ids:string[];pinned:boolean;atoms:Atom[];onpatch:(patch:Partial<Pick<Atom,'importance'|'appearance'>>)=>Promise<void>;onmove:(target:string)=>Promise<void>;onaction:(action:AtomState|'resume'|'pin'|'unpin'|'delete')=>Promise<void>;onclose:()=>void}=$props();let confirm=$state(false),busy=$state(false),error=$state(''),destination=$state((()=>destinationOnly)()),query=$state('');
 let root:HTMLDivElement;onMount(()=>root.focus());
 function keys(e:KeyboardEvent){if(e.key!=='Tab')return;const buttons=[...root.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select:not([disabled]),summary')].filter(el=>el.getClientRects().length);if(e.shiftKey&&(document.activeElement===buttons[0]||document.activeElement===root)){e.preventDefault();buttons.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===buttons.at(-1)){e.preventDefault();buttons[0]?.focus();}}
 async function act(action:AtomState|'resume'|'pin'|'unpin'|'delete'){busy=true;try{await onaction(action);onclose();}catch(e){error=(e as Error).message;}finally{busy=false;}}
</script>

<div class="context-scrim" use:surface={{close:()=>{if(confirm)confirm=false;else if(destination&&!destinationOnly)destination=false;else onclose();},blocked:()=>busy}}><div class="atom-menu" bind:this={root} tabindex="-1" onkeydown={keys} role="dialog" aria-label="Действия с ветвью" aria-modal="true"><div class="context-heading"><strong>Выделено: {ids.length}</strong><button aria-label="Закрыть" disabled={busy} onclick={onclose}>×</button></div>{#if destination}<label class="stack">Найти группу<input aria-label="Найти группу" bind:value={query}/></label>{#each atoms.filter(a=>!ids.includes(a.id)&&a.title.toLocaleLowerCase().includes(query.toLocaleLowerCase())) as atom}<button disabled={busy} onclick={async()=>{busy=true;error='';try{await onmove(atom.id);onclose();}catch(e){error=(e as Error).message;}finally{busy=false;}}}>{atom.title}</button>{/each}<button disabled={busy} onclick={()=>{if(destinationOnly)onclose();else destination=false;}}>Назад</button>{:else if confirm}<p>Удалить {ids.length} атомов ветви и их связи?</p><button class="danger-button" disabled={busy} onclick={()=>act('delete')}>Удалить ветвь</button><button onclick={()=>confirm=false}>Отмена</button>{:else}<div class="state-shortcuts">{#each [['normal','Обычный'],['now','Сейчас'],['paused','Пауза'],['archived','Архив']] as [state,label]}<button disabled={busy} onclick={()=>act(state as AtomState)}>{label}</button>{/each}{#if atoms.some(a=>ids.includes(a.id)&&a.state==='paused')}<button disabled={busy} onclick={()=>act('resume')}>Возобновить</button>{/if}<button disabled={busy} onclick={()=>act(pinned?'unpin':'pin')}>{pinned?'Открепить':'Закрепить'}</button><button disabled={busy} onclick={()=>destination=true}>В другую группу…</button><button class="danger" disabled={busy} onclick={()=>confirm=true}>Удалить…</button></div><SelectionOptions {onpatch} bind:busy/>{/if}{#if error}<p role="alert">{error}</p>{/if}</div></div>
