<script lang="ts">
 import {Marked} from 'marked';
 import {sanitizeHTML} from './markdown';
 import {listVaults,storedBytes,notePath,resolvePath,resolveAtom} from '../core/vault';
 import type {Atom,StorageAdapter} from '../core/model';
 import {download} from '../core/backup';
 let {content,source,atoms,storage,onopen}:{content:string;source:Atom;atoms:Atom[];storage:StorageAdapter;onopen:(id:string)=>void}=$props();let root:HTMLDivElement;let error=$state('');
 const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
 const html=$derived.by(()=>{const link=(target:string,label:string,embed=false)=>{const atom=resolveAtom(target.split('#')[0],source,atoms);if(atom)return `<a href="#" data-atom="${escape(atom.id)}">${label}</a>`;if(/^(https?:|mailto:)/i.test(target))return `<a href="${escape(target)}" target="_blank" rel="noopener noreferrer">${label}</a>`;return `<a href="#" data-file="${escape(target.split('#')[0])}" data-embed="${embed}">${label}</a>`;};const parser=new Marked({renderer:{link({href,tokens}){return link(href,this.parser.parseInline(tokens));},image({href,text}){return link(href,escape(text||href),true);}}});parser.use({extensions:[{name:'wiki',level:'inline',start:src=>src.indexOf('[['),tokenizer(src){const m=/^(!?)\[\[([^\]\n]+)\]\]/.exec(src);if(m)return{type:'wiki',raw:m[0],target:m[2].split('|')[0],label:m[2].split('|')[1]||m[2],embed:!!m[1]};},renderer(token){return link(token.target,escape(token.label),token.embed);}}]});return sanitizeHTML(parser.parse(content,{async:false}) as string);});
 $effect(()=>{html;const vault=notePath(source);let disposed=false;const urls:string[]=[];queueMicrotask(async()=>{if(!root||!vault)return;try{const v=(await listVaults(storage)).find(v=>v.id===vault.vault);if(!v||disposed)return;for(const el of root.querySelectorAll<HTMLAnchorElement>('a[data-file]')){const path=resolvePath(el.dataset.file!,vault.path,v.files.map(f=>f.path));const file=v.files.find(f=>f.path===path);if(!file)continue;el.onclick=async e=>{e.preventDefault();try{download(file.path.split('/').at(-1)!,await storedBytes(storage,file),'application/octet-stream');}catch(e){error=(e as Error).message;}};if(el.dataset.embed==='true'&&/\.(png|jpe?g|gif|webp|avif)$/i.test(file.path)){const bytes=await storedBytes(storage,file);if(disposed)return;const ext=file.path.split('.').at(-1)!.toLowerCase();const url=URL.createObjectURL(new Blob([bytes.buffer],{type:'image/'+(ext==='jpg'?'jpeg':ext)}));urls.push(url);const img=document.createElement('img');img.src=url;img.alt=el.textContent||file.path;img.style.maxWidth='100%';el.replaceChildren(img);}}}catch(e){if(!disposed)error=(e as Error).message;}});return()=>{disposed=true;urls.forEach(url=>URL.revokeObjectURL(url));};});
 function navigate(e:MouseEvent){const a=(e.target as Element).closest<HTMLAnchorElement>('a');if(a?.dataset.atom){e.preventDefault();onopen(a.dataset.atom);}else if(a?.dataset.file&&!a.onclick){e.preventDefault();error='Файл не найден: '+a.dataset.file;}}
</script>
<!-- svelte-ignore a11y_no_static_element_interactions (Delegates ordinary anchor navigation.) -->
<!-- svelte-ignore a11y_click_events_have_key_events (Anchors retain native keyboard activation.) -->
<div class="markdown note-content" bind:this={root} onclick={navigate}>{@html html}{#if error}<p role="alert">{error}</p>{/if}</div>
