<script lang="ts">
 import type {Core} from '../core/core';
 import type {PluginRuntime} from '../plugins/runtime';
 import {templates} from '../plugins/builtins';
 import {dynamicsPlugins} from '../plugins/dynamics';
 import {daily} from '../plugins/daily';
 import {dailyTasks} from '../plugins/daily-tasks';
 import {communityPlugin} from '../plugins/sandbox';
 import {validateManifest,type Manifest} from '../plugins/api';
 import {download,exportBackup,parseBackup,importBackup} from '../core/backup';
 import type {Snapshot} from '../core/model';
 import {onMount} from 'svelte';
 import Behavior from './Behavior.svelte';
 import Themes from './Themes.svelte';
 import Vaults from './Vaults.svelte';
 import NativeBackup from './NativeBackup.svelte';
 import type {Preferences} from '../core/preferences';
 import {readPackage,type PluginPackage} from '../plugins/package';
 let {core,runtime,persistent,prefs,onclose,onpersist,onnotify}:{core:Core;runtime:PluginRuntime;persistent:boolean;prefs:Preferences;onclose:()=>void;onpersist:()=>Promise<void>;onnotify:(s:string)=>void}=$props();
 let page=$state<'general'|'plugins'>('general');let selectedPlugin=$state<Manifest|null>(null);let values=$state<Record<string,boolean|string>>({});
 async function openPlugin(manifest:Manifest){const next:Record<string,boolean|string>={};for(const field of manifest.settings||[])next[field.key]=await core.storage.getSetting<boolean|string>(`plugin:${manifest.id}:${field.key}`)??field.default;values=next;selectedPlugin=manifest;}
 const buildLabel=import.meta.env.VITE_BUILD_LABEL||'0.2.0';
 let packageData=$state<PluginPackage|null>(null);let developerMode=$state(false);
 let revision=$state(0);let error=$state('');let busy=$state(false);let installed=$state<{manifest:Manifest;source:string;style?:string;assets?:Record<string,number[]>;enabled:boolean}[]>([]);let pendingManifest=$state<Manifest|null>(null);let pendingSource=$state('');let importData=$state<Snapshot|null>(null);let backups=$state<{at:string;data:Snapshot}[]>([]);let usage=$state('');let root:HTMLDivElement;
 onMount(()=>{root.focus();Promise.all([core.storage.getSetting<typeof installed>('community-plugins'),core.storage.getSetting<typeof backups>('backups'),navigator.storage.estimate()]).then(([plugins,copies,estimate])=>{installed=plugins||[];backups=copies||[];usage=`${((estimate.usage||0)/1024/1024).toFixed(1)} МБ занято`;}).catch(e=>error=e.message);});
 async function run(fn:()=>Promise<unknown>){busy=true;error='';try{await fn();revision++;}catch(e){error=(e as Error).message;}finally{busy=false;}}
 async function checkpoint(){const copies=await core.storage.getSetting<typeof backups>('backups')||[];backups=[{at:new Date().toISOString(),data:core.data},...copies].slice(0,3);await core.storage.transaction([{kind:'setting',key:'backups',value:$state.snapshot(backups)}]);}
 async function toggleBuiltin(id:string){if(runtime.active.has(id))runtime.disable(id);else await runtime.enable([templates,daily,dailyTasks,...dynamicsPlugins].find(p=>p.manifest.id===id)!);await core.storage.transaction([{kind:'setting',key:'disabled-builtins',value:[templates,daily,dailyTasks,...dynamicsPlugins].filter(p=>!runtime.active.has(p.manifest.id)).map(p=>p.manifest.id)}]);}
 async function persistPlugins(){await core.storage.transaction([{kind:'setting',key:'community-plugins',value:$state.snapshot(installed)}]);}
 async function fileText(e:Event){const input=e.target as HTMLInputElement;const file=input.files?.[0];input.value='';if(!file)throw Error('Файл не выбран.');if(file.size>50_000_000)throw Error('Файл слишком большой.');return file.text();}
 function keys(e:KeyboardEvent){if(e.key==='Escape'&&!busy)onclose();if(e.key==='Tab'){const els=[...root.querySelectorAll<HTMLElement>('button:not([disabled]),input,select,summary')].filter(el=>el.getClientRects().length);if(e.shiftKey&&(document.activeElement===els[0]||document.activeElement===root)){e.preventDefault();els.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===els.at(-1)){e.preventDefault();els[0]?.focus();}}}
</script>
<div class="scrim"><div class="editor settings" bind:this={root} tabindex="-1" role="dialog" aria-modal="true" aria-label="Настройки" onkeydown={keys}>
 <div class="row"><h2>Ваше пространство</h2><button aria-label="Закрыть настройки" disabled={busy} onclick={onclose}>×</button></div>
 {#if error}<p role="alert" class="inline-error">{error}</p>{/if}
 {#if page==='general'}<button onclick={()=>page='plugins'}>Плагины →</button>
 <Themes {core} {prefs}/><Behavior {core} {prefs} providers={runtime.providers} onerror={e=>error=e.message}/>
 <section><small>НА ЭТОМ УСТРОЙСТВЕ</small><h3>{persistent?'Хранилище защищено':'Локальное хранилище'}</h3><p>{usage}. Карта остаётся на устройстве. Без аккаунта и отправки заметок на сервер.</p>{#if !persistent}<p>Браузер пока не предоставил защиту от автоматической очистки при нехватке места.</p><button disabled={busy} onclick={()=>run(onpersist)}>Запросить защиту хранилища</button>{/if}</section>
 <NativeBackup {core} bind:busy/><Vaults {core}/><details class="legacy-backup"><summary>Дополнительные форматы и снимки</summary><section><p>JSON переносит атомы и связи. Для всех данных используйте полную копию выше.</p><div class="button-wrap"><button disabled={busy} onclick={()=>download('phosphora-map.json',exportBackup(core.data))}>Экспорт карты</button><button disabled={busy} onclick={()=>run(async()=>download('phosphora.sqlite3',await core.storage.exportDatabase(),'application/vnd.sqlite3'))}>Скачать SQLite</button><label class="file-button">Импорт карты<input type="file" accept=".json,application/json" disabled={busy} onchange={e=>run(async()=>{importData=parseBackup(await fileText(e));})}/></label></div>
 {#if importData}<div class="confirm"><p>В копии {importData.atoms.length} атомов и {importData.links.length} связей. Импорт добавит отсутствующие записи. Существующие атомы сохранят свои текущие версии.</p><button disabled={busy} onclick={()=>run(async()=>{await checkpoint();const n=await importBackup(core,$state.snapshot(importData!));importData=null;onnotify(`Добавлено атомов: ${n}`);})}>Добавить в карту</button><button onclick={()=>importData=null}>Отмена</button></div>{/if}
 <details><summary>Локальные снимки · {backups.length}</summary><p>До трёх последних снимков перед удалением или импортом. Они не защищают от потери устройства.</p><button disabled={busy} onclick={()=>run(checkpoint)}>Создать снимок</button>{#each backups as copy}<button disabled={busy} onclick={()=>run(async()=>{importData=parseBackup(exportBackup(copy.data));})}>Восстановить отсутствующее · {new Date(copy.at).toLocaleString('ru-RU')}</button>{/each}</details></section></details>
 {/if}
 {#if page==='plugins'}<button onclick={()=>{if(selectedPlugin)selectedPlugin=null;else page='general';}}>← {selectedPlugin?'Все плагины':'Настройки'}</button>
 {#if selectedPlugin}<section><h3>{selectedPlugin.name}</h3><p>Настройки сохраняются автоматически.</p>{#each selectedPlugin.settings||[] as field}<label>{field.label}{#if field.type==='boolean'}<input type="checkbox" checked={Boolean(values[field.key])} disabled={busy} onchange={e=>{const checked=e.currentTarget.checked;run(async()=>{await core.storage.transaction([{kind:'setting',key:`plugin:${selectedPlugin!.id}:${field.key}`,value:checked}]);values[field.key]=checked;});}}/>{:else}<input type="text" value={String(values[field.key]??'')} maxlength="200" disabled={busy} onchange={e=>{const value=e.currentTarget.value;run(async()=>{await core.storage.transaction([{kind:'setting',key:`plugin:${selectedPlugin!.id}:${field.key}`,value}]);values[field.key]=value;});}}/>{/if}</label>{/each}</section>{:else}
 <section><small>РАСШИРЕНИЯ</small><p>Встроенные возможности используют тот же публичный API.</p>{#key revision}{#each [templates,daily,dailyTasks,...dynamicsPlugins] as plugin}<div class="plugin-row"><div><strong>{plugin.manifest.name}</strong>{#if plugin.manifest.settings?.length}<button disabled={busy} onclick={()=>run(()=>openPlugin(plugin.manifest))}>Настройки</button>{/if}<small>{plugin.manifest.description}</small></div><button disabled={busy} aria-pressed={runtime.active.has(plugin.manifest.id)} onclick={()=>run(()=>toggleBuiltin(plugin.manifest.id))}>{runtime.active.has(plugin.manifest.id)?'Выключить':'Включить'}</button></div>{/each}{/key}
 {#each installed as plugin,i}<div class="plugin-row"><div><strong>{plugin.manifest.name}</strong>{#if plugin.manifest.settings?.length}<button disabled={busy} onclick={()=>run(()=>openPlugin(plugin.manifest))}>Настройки</button>{/if}<small>{plugin.manifest.permissions.join(', ')}</small></div><button disabled={busy} onclick={()=>run(async()=>{if(plugin.enabled)runtime.disable(plugin.manifest.id);else await runtime.enable(communityPlugin(plugin.manifest,plugin.source,plugin));installed[i].enabled=!plugin.enabled;await persistPlugins();})}>{plugin.enabled?'Выключить':'Включить'}</button><button disabled={busy} aria-label={`Удалить плагин ${plugin.manifest.name}`} onclick={()=>run(async()=>{runtime.disable(plugin.manifest.id);installed=installed.filter((_,j)=>j!==i);await persistPlugins();})}>×</button></div>{/each}
 <details><summary>Установить плагин</summary><p>Выберите один файл .phosphora. Перед установкой мы покажем разрешения.</p><label class="file-button">Выбрать .phosphora<input type="file" accept=".phosphora,.phosphored" aria-label="Пакет плагина" disabled={busy} onchange={e=>run(async()=>{const input=e.currentTarget;const file=input.files?.[0];input.value='';if(!file)return;if(!/[.](phosphora|phosphored)$/i.test(file.name))throw Error('Expected .phosphora');packageData=readPackage(new Uint8Array(await file.arrayBuffer()));pendingManifest=packageData.manifest;pendingSource=packageData.source;})}/></label><label>Режим разработчика<input type="checkbox" bind:checked={developerMode}/></label>{#if developerMode}<label class="file-button">Manifest.json<input type="file" accept=".json" onchange={e=>run(async()=>{const m=JSON.parse(await fileText(e));validateManifest(m);if(m.id.startsWith('builtin.'))throw Error('Reserved plugin ID');pendingManifest=m;})}/></label><label class="file-button">Main.js<input type="file" accept=".js,.mjs" onchange={e=>run(async()=>pendingSource=await fileText(e))}/></label>{/if}
 {#if pendingManifest&&pendingSource}<div class="confirm"><h3>{pendingManifest.name}</h3><p>Разрешения: {pendingManifest.permissions.join(', ')||'нет'}. {pendingManifest.permissions.includes('atoms.write')?'Плагин сможет создавать, менять и удалять атомы.':''}</p><button disabled={busy} onclick={()=>run(async()=>{if(installed.some(p=>p.manifest.id===pendingManifest!.id))throw Error('Сначала удалите установленную версию этого плагина.');await runtime.enable(communityPlugin($state.snapshot(pendingManifest!),pendingSource,$state.snapshot(packageData)||undefined));installed=[...installed,{manifest:$state.snapshot(pendingManifest!),source:pendingSource,style:packageData?.style,assets:packageData?.assets,enabled:true}];await persistPlugins();pendingManifest=null;pendingSource='';packageData=null;onnotify('Плагин установлен. Команды доступны в меню карты.');})}>Разрешить и установить</button></div>{/if}</details></section>
 {/if}{/if}
 {#if page==='general'}<section><small>КАК ПОЛЬЗОВАТЬСЯ</small><p>Нажатие открывает атом. Долгое нажатие или правая кнопка мыши — меню действий. Двойное нажатие пустого места создаёт атом. Два пальца — масштаб, один — перемещение карты. При переносе атома появляются зоны смены состояния.</p><p>После поиска: Enter — редактор, 1–4 — состояние. Ctrl/⌘ + K — поиск, Ctrl/⌘ + Enter — сохранить. Издалека связанные атомы объединяются в кластеры.</p><p class="muted">Phosphora {buildLabel} · схема 3</p></section>
 {/if}</div></div>
