<script lang="ts">
 import {onMount} from 'svelte';
 import {tasksAt,taskHistory,type NoteTask} from '../core/tasks';
 import type {Atom,Snapshot,AtomState} from '../core/model';
 import type {Core} from '../core/core';
 let {data,core,onopen}:{data:Snapshot;core:Core;onopen:(id:string)=>void}=$props();
 let clock=$state(Date.now());onMount(()=>{const timer=setInterval(()=>clock=Date.now(),60000);return()=>clearInterval(timer);});
 const lanes=[['now','Сейчас'],['normal','Обычные'],['archived','Архив']] as const;
 let busy=$state(false),error=$state(''),drag=$state<{id:string;title:string;pointer:number;lane:string}|null>(null),period=$state(7);
 const groups=$derived(data.atoms.map(atom=>({atom,tasks:tasksAt(atom,new Date(clock))})).filter(group=>group.tasks.length));
 async function run(fn:()=>Promise<unknown>){if(busy)return;busy=true;error='';try{await fn();}catch(e){error=(e as Error).message;}finally{busy=false;}}
 function history(task:NoteTask){return taskHistory(task,period as 7|30,new Date(clock));}
 function completed(task:NoteTask){return history(task).filter(day=>day.completed).length;}
 function begin(e:PointerEvent,atom:Atom){if(busy||e.button!==0)return;e.preventDefault();(e.currentTarget as HTMLElement).focus({preventScroll:true});(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);drag={id:atom.id,title:atom.title,pointer:e.pointerId,lane:''};}
 function move(e:PointerEvent){if(!drag||e.pointerId!==drag.pointer)return;const lane=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-task-lane]')?.getAttribute('data-task-lane')||'';drag={...drag,lane};}
 function end(e:PointerEvent){if(!drag||e.pointerId!==drag.pointer)return;move(e);const value=drag;drag=null;if(value?.lane)void run(()=>core.setState(value.id,value.lane as AtomState));}
</script>
<svelte:window onkeydown={e=>{if(e.key==='Escape')drag=null;}} onpointerdown={e=>{if(drag&&e.pointerId!==drag.pointer)drag=null;}}/>
<section class="kanban" aria-label="Канбан">
 <div class="board-heading"><div><small>ЗАДАЧИ ВАШИХ АТОМОВ</small><h1>Канбан</h1></div><span>{groups.reduce((n,g)=>n+g.tasks.filter(t=>!t.checked).length,0)} незавершённых</span></div>
 {#if error}<p role="alert">{error}<button onclick={()=>error=''}>Закрыть</button></p>{/if}
 {#if drag}<div class="task-destinations" aria-label="Куда переместить"><strong>{drag.title}</strong><div>{#each lanes as [state,label]}<button data-task-lane={state} class:active={drag.lane===state}>{label}</button>{/each}</div></div>{/if}
 {#snippet group(atom:Atom,tasks:NoteTask[],paused=false)}
 <article class="task-group" data-source={atom.id}>
 <div class="group-heading"><button class="group-title" onclick={()=>onopen(atom.id)}>{atom.title}</button><button class="group-drag" aria-label={`Переместить группу ${atom.title}`} title="Перетяните в колонку" disabled={busy} onpointerdown={e=>begin(e,atom)} onpointermove={move} onpointerup={end} onpointercancel={()=>drag=null}>&#8942;&#8942;</button></div>
 <div class="group-controls"><select aria-label={`Состояние ${atom.title}`} value={atom.state} disabled={busy} onchange={e=>run(()=>core.setState(atom.id,e.currentTarget.value as AtomState))}>{#each lanes as [state,label]}<option value={state}>{label}</option>{/each}</select>{#if paused}<button disabled={busy} onclick={()=>run(()=>core.setPaused(atom.id,false))}>Возобновить</button>{/if}</div>
 {#each tasks as task (task.id)}
 <div class="board-task"><label><input type="checkbox" checked={task.checked} disabled={busy} aria-label={task.text} onchange={e=>run(()=>core.setTask(atom.id,task.id,{checked:e.currentTarget.checked}))}/><span class:done={task.checked}>{task.text}</span></label>
 <details><summary aria-label={`Повторение ${task.text}`}>{task.recurrence==='daily'?'Ежедневно':task.recurrence==='weekly'?'Еженедельно':'Повторение'}</summary><label>Повторение <select aria-label={`Повтор ${task.text}`} value={task.recurrence||''} disabled={busy} onchange={e=>run(()=>core.setTask(atom.id,task.id,{recurrence:e.currentTarget.value as 'daily'|'weekly'||null}))}><option value="">Однократно</option><option value="daily">Ежедневно</option><option value="weekly">Еженедельно</option></select></label>{#if task.recurrence}<label>История <select aria-label={`Период ${task.text}`} bind:value={period}><option value={7}>7 дней</option><option value={30}>30 дней</option></select></label><div class="task-history" role="list" aria-label="История">{#each history(task) as day (day.key)}<span role="listitem" class:complete={day.completed} class:current={day.current} title={`${day.key}: ${day.completed?'✓':'—'}`} aria-label={`${day.key}: ${day.completed?'✓':'—'}`}>{day.completed?'✓':'·'}</span>{/each}</div><p>{completed(task)} выполнений за {period} дней</p>{/if}</details>
 </div>{/each}
 </article>
 {/snippet}
 {#if !groups.length}<div class="board-empty"><h2>Задачи живут в ваших мыслях</h2><p>Добавьте список задач в текст любого атома. Он появится здесь целой группой.</p></div>{:else}<div class="board-lanes">{#each lanes as [state,label]}<section class="board-lane" data-task-lane={state} aria-label={label}><h2>{label}<small>{groups.filter(g=>!g.atom.paused&&g.atom.state===state).length}</small></h2>{#each groups.filter(g=>!g.atom.paused&&g.atom.state===state) as g (g.atom.id)}{@render group(g.atom,g.tasks)}{:else}<p class="lane-empty">Пока пусто</p>{/each}</section>{/each}</div>
 {@const paused=groups.filter(g=>g.atom.paused)}{#if paused.length}<details class="paused-groups"><summary>На паузе ({paused.length})</summary>{#each paused as g (g.atom.id)}{@render group(g.atom,g.tasks,true)}{/each}</details>{/if}{/if}
</section>
<style>
 .task-history{display:flex;flex-wrap:wrap;gap:4px;margin:12px 0}.task-history span{display:grid;place-items:center;width:24px;height:24px;border-radius:7px;background:var(--theme-background);color:var(--theme-muted);font-size:12px}.task-history .complete{background:var(--theme-accent);color:var(--theme-background)}.task-history .current{outline:1px solid var(--theme-muted);outline-offset:1px}
 .kanban{position:absolute;inset:90px 0 120px;z-index:2;overflow:auto;padding:20px clamp(16px,3vw,42px) 50px;background:var(--theme-background);overscroll-behavior:contain;animation:board-in .18s ease-out}.board-heading{display:flex;align-items:center;justify-content:space-between;margin-bottom:26px;gap:12px}.board-heading h1{font-size:30px;letter-spacing:-1px;margin:6px 0}.board-heading small,.board-heading>span{font-size:11px;color:var(--theme-muted)}.board-lanes{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.board-lane{min-width:0}.board-lane h2{font-size:16px;font-weight:500;margin:0 0 14px;display:flex;justify-content:space-between;align-items:center}.board-lane h2 small{font-size:11px;color:var(--theme-muted)}.task-group{border:1px solid var(--theme-border);border-radius:20px;background:var(--theme-surface);padding:14px;margin-bottom:14px}.group-heading{display:flex;align-items:center;gap:6px}.group-title{border:0;background:none;text-align:left;font-weight:600;padding:6px 0;flex:1;min-width:0;overflow-wrap:anywhere}.group-drag{touch-action:none;padding:6px 10px;font-size:20px;border:0;background:none;min-width:44px}.group-controls{display:flex;gap:8px;margin:4px 0 12px}.group-controls select{font-size:11px;padding:6px 10px;flex:1;min-width:0}.group-controls button{font-size:11px;padding:6px 10px}.board-task{padding:8px 0}.board-task>label{display:flex;gap:10px;align-items:center;font-size:14px;line-height:1.5;overflow-wrap:anywhere}.board-task input{flex:0 0 24px;width:24px;height:24px;min-height:24px;accent-color:var(--theme-accent);cursor:pointer}.done{text-decoration:line-through;color:var(--theme-muted)}.board-task details{border:0;padding-left:34px;font-size:11px}.board-task summary{padding:4px 0;min-height:32px;font-size:11px;color:var(--theme-muted)}.board-task details label{display:flex;align-items:center;justify-content:space-between;gap:8px;margin:8px 0}.board-task details select{font-size:11px;padding:6px;max-width:65%}.board-task details p{font-size:11px}.lane-empty{font-size:12px;color:var(--theme-muted);padding:10px}.paused-groups{margin-top:30px}.paused-groups>.task-group{max-width:440px;opacity:.8}.board-empty{max-width:420px;margin:60px auto;text-align:center}.task-destinations{position:fixed;top:90px;left:50%;transform:translateX(-50%);z-index:20;max-width:95vw;padding:12px;border-radius:20px;background:var(--theme-surface);box-shadow:0 8px 40px #0006}.task-destinations strong{display:block;font-size:12px;max-width:280px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;margin-bottom:8px}.task-destinations>div{display:flex;gap:5px}.task-destinations button{padding:8px;font-size:12px}@media(max-width:650px){.kanban{top:85px}.board-lanes{grid-template-columns:1fr;gap:28px}.board-heading{margin-bottom:20px}.task-destinations{top:80px}}@keyframes board-in{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:none}}@media(prefers-reduced-motion:reduce){.kanban{animation:none}}
</style>
