import {safePhysics} from '../graph/physics';
import type {Core} from '../core/core';
import {GraphProviders} from '../graph/providers';
import {installStyles} from './styles';
import {validateManifest,type Plugin,type PluginAPI,type Manifest,type Permission,type Command,type AtomType,type Layout,type PluginView} from './api';
export class PluginRuntime {
 providers=new GraphProviders();
 commands=new Map<string,Command>();types=new Map<string,AtomType>();layouts=new Map<string,Layout>();actions=new Map<string,Command>();views=new Map<string,PluginView>();
 active=new Map<string,{manifest:Manifest;dispose:()=>void}>();
 constructor(private core:Core,private host:{focus:(id:string)=>void;notify:(text:string)=>void;changed:()=>void}){}
 async enable(plugin:Plugin){validateManifest(plugin.manifest);if(this.active.has(plugin.manifest.id))return;const cleanup:(()=>void)[]=[];let enabled=true,preparing=false;const m=plugin.manifest;
 const check=(p:Permission,write=false)=>{if(!enabled)throw Error('Плагин выключен.');if(!m.permissions.includes(p))throw Error(`Плагину ${m.id} требуется разрешение ${p}`);if(preparing&&(write||p==='atoms.write'||p==='links.write'))throw Error('Draft policy must return effects instead of writing during preparation.');};
 const register=<T extends {id:string}>(map:Map<string,T>,item:T,p:Permission)=>{check(p);if(!item||typeof item.id!=='string'||!item.id||item.id.length>100)throw Error('Некорректный ID расширения.');const identity:unknown=map;const method=identity===this.providers.structure?'arrange':identity===this.providers.physics?'step':identity===this.providers.layout?'place':identity===this.providers.clustering?'project':identity===this.providers.reduction?'reduce':identity===this.providers.weight?'weigh':identity===this.views?'render':identity===this.types||identity===this.providers.tools?'':'run';if(typeof (item as any).name!=='string'||!(item as any).name||method&&typeof (item as any)[method]!=='function')throw Error('Invalid extension contract');const id=m.id+':'+item.id;if(map.has(id))throw Error('ID уже зарегистрирован.');map.set(id,{...item,id});this.host.changed();const off=()=>{map.delete(id);this.host.changed();};cleanup.push(off);return off;};
 const scopedStorage=(permission:Permission)=>({get:async<T>(key:string)=>{check(permission);return this.core.storage.getSetting<T>(`plugin:${m.id}:${key}`);},set:async(key:string,value:unknown)=>{check(permission,true);if(typeof key!=='string'||key.length>150)throw Error('Слишком длинный ключ.');await this.core.storage.transaction([{kind:'setting',key:`plugin:${m.id}:${key}`,value}]);}});const storage=scopedStorage('storage');
 const clone=<T>(v:T):T=>structuredClone(v);
 const api:PluginAPI={
 atoms:{registerDraftPolicy:policy=>{
  for(const permission of ['atoms.read','atoms.write','links.read','links.write'] as Permission[])check(permission);
  if(!policy||typeof policy.id!=='string'||!policy.id||policy.id.length>100||typeof policy.name!=='string'||!policy.name||typeof policy.prepare!=='function')throw Error('Invalid draft policy');
  const off=this.core.drafts.register({...policy,id:m.id+':'+policy.id,prepare:async context=>{
   check('atoms.write');preparing=true;
   try{const result=await policy.prepare(context);if(!enabled)throw Error('Плагин выключен.');return clone(result);}finally{preparing=false;}
  }});cleanup.push(off);return off;
 },list:async()=>{check('atoms.read');return clone(this.core.data.atoms);},get:async id=>{check('atoms.read');return clone(this.core.data.atoms.find(a=>a.id===id));},search:async q=>{check('atoms.read');return clone(this.core.search(q));},create:async(input,parent)=>{check('atoms.write');return clone(await this.core.create(clone(input),parent));},update:async(id,patch)=>{check('atoms.write');return clone(await this.core.update(id,clone(patch)));},setTask:async(id,taskId,patch)=>{check('atoms.write');return clone(await this.core.setTask(id,taskId,patch));},setPaused:async(id,paused)=>{check('atoms.write');return clone(await this.core.setPaused(id,paused));},setState:async(id,state)=>{check('atoms.write');return clone(await this.core.setState(id,state));},delete:async id=>{check('atoms.write');await this.core.delete(id);}},
 links:{list:async()=>{check('links.read');return clone(this.core.data.links);},create:async(from,to,relation)=>{check('links.write');return clone(await this.core.link(from,to,relation));},delete:async id=>{check('links.write');await this.core.unlink(id);}},
 events:{on:(event,fn)=>{check(event.startsWith('link:')?'links.read':event.startsWith('graph:')?'graph':event.startsWith('preferences:')?'settings':'atoms.read');const off=this.core.on(event,fn);cleanup.push(off);return off;}},
 commands:{add:c=>register(this.commands,c,'ui')},types:{register:t=>register(this.types,t,'ui')},
 graph:{registerMapTool:p=>{if(!p||!['lasso','ambient-lens'].includes(p.kind))throw Error('Invalid map tool');return register(this.providers.tools,p,'graph');},registerStructuralProvider:p=>{check('graph');if(!p||typeof p.physicsId!=='string'||!p.physicsId||typeof p.description!=='string'||p.description.length>500||!p.defaults)throw Error('Invalid structural provider metadata');const physicsId=p.physicsId.includes(':')?p.physicsId:m.id+':'+p.physicsId;return register(this.providers.structure,{...p,physicsId,defaults:safePhysics(p.defaults)},'graph');},focus:id=>{check('graph');this.host.focus(id);},registerLayout:l=>register(this.layouts,l,'graph'),registerPhysicsProvider:p=>register(this.providers.physics,p,'graph'),registerLayoutProvider:p=>register(this.providers.layout,p,'graph'),registerClusteringProvider:p=>register(this.providers.clustering,p,'graph'),registerLinkReductionProvider:p=>register(this.providers.reduction,p,'graph'),registerNodeWeightProvider:p=>register(this.providers.weight,p,'graph')},
 ui:{notify:text=>{check('ui');this.host.notify(String(text).slice(0,1000));},registerContextAction:c=>register(this.actions,c,'ui')},views:{register:v=>{if(v.onAction!==undefined&&typeof v.onAction!=='function')throw Error('Invalid view action');return register(this.views,{...v,render:()=>{check('ui');return v.render();},onAction:v.onAction?async(action,values)=>{check('ui');if(typeof action!=='string'||action.length>300||Object.keys(values).length>40||Object.values(values).some(value=>typeof value!=='string'||value.length>10000))throw Error('Invalid view input');return v.onAction!(action,values);}:undefined},'ui');}} ,storage,settings:scopedStorage('settings'),assets:{list:async()=>{if(!enabled)throw Error('Плагин выключен.');return Object.keys(plugin.resources?.assets||{});},read:async path=>{if(!enabled)throw Error('Плагин выключен.');const asset=plugin.resources?.assets?.[path];if(!asset)throw Error('Ресурс отсутствует в пакете.');return Uint8Array.from(asset);}}};
 try{if(plugin.resources?.style){check('ui');cleanup.push(installStyles(m.id,plugin.resources.style));}const off=await plugin.activate(api);if(off)cleanup.push(off);this.active.set(m.id,{manifest:m,dispose:()=>{enabled=false;for(const fn of cleanup.reverse())try{fn();}catch(e){console.error(e);}}});this.host.changed();}catch(e){enabled=false;for(const fn of cleanup.reverse())fn();throw e;}
 }
 disable(id:string){this.active.get(id)?.dispose();this.active.delete(id);this.host.changed();}
 dispose(){for(const id of [...this.active.keys()])this.disable(id);}
}
