import type {Manifest,Plugin,PluginAPI} from './api';
// Community code runs only in a Worker inside an opaque-origin sandbox.
// The iframe contains our fixed bridge, never community HTML or JavaScript.
const frameHTML=`<!doctype html><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline' blob:; worker-src blob:; connect-src 'none'; img-src 'none'; style-src 'none'; child-src 'none';"><script>
addEventListener('message',function init(e){if(e.source!==parent||!e.ports[0])return;removeEventListener('message',init);const port=e.ports[0];try{const worker=new Worker(URL.createObjectURL(new Blob([e.data],{type:'text/javascript'})));port.onmessage=e=>worker.postMessage(e.data);worker.onmessage=e=>port.postMessage(e.data);worker.onerror=e=>port.postMessage({fatal:e.message||'Sandbox Worker failed'});port.start();}catch(e){port.postMessage({fatal:String(e)});}});
</script>`;
const workerBootstrap=`
let seq=0;const pending=new Map(),callbacks=new Map();
function encode(v){if(typeof v==='function'){const id=++seq;callbacks.set(id,v);return {__callback:id};}if(Array.isArray(v))return v.map(encode);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,encode(x)]));return v;}
function call(path,...args){return new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});postMessage({id,path,args:encode(args)});});}
const app={};for(const [section,methods] of Object.entries({atoms:['registerDraftPolicy','list','get','create','update','setState','delete','search'],links:['list','create','delete'],events:['on'],commands:['add'],types:['register'],graph:['registerStructuralProvider','focus','registerLayout','registerPhysicsProvider','registerLayoutProvider','registerClusteringProvider','registerLinkReductionProvider','registerNodeWeightProvider'],ui:['notify','registerContextAction'],views:['register'],storage:['get','set'],settings:['get','set'],assets:['list','read']})){app[section]={};for(const method of methods)app[section][method]=(...args)=>call(section+'.'+method,...args);}
onmessage=async({data:m})=>{if(m.invoke){try{postMessage({invoked:m.invoke,result:await callbacks.get(m.callback)?.(...m.args)});}catch(e){postMessage({invoked:m.invoke,error:String(e)});}return;}const p=pending.get(m.id);if(p){pending.delete(m.id);if(m.error)p.reject(Error(m.error));else p.resolve(m.result&&m.result.__dispose?()=>call('dispose',m.result.__dispose):m.result);}};
`;
export function communityPlugin(manifest:Manifest,source:string,resources?:{style?:string;assets?:Record<string,number[]>}):Plugin{return{manifest,resources,activate:async(api:PluginAPI)=>{
 if(source.length>1_000_000)throw Error('Плагин превышает 1 МБ.');
 const frame=document.createElement('iframe');frame.sandbox.add('allow-scripts');frame.hidden=true;frame.srcdoc=frameHTML;document.body.append(frame);
 const channel=new MessageChannel();let sequence=0,disposed=false;const disposers=new Map<number,()=>void>();const invocations=new Map<number,{resolve:(v:any)=>void;reject:(e:Error)=>void;timer:ReturnType<typeof setTimeout>}>();
 const dispose=()=>{if(disposed)return;disposed=true;channel.port1.close();frame.remove();for(const fn of disposers.values())fn();for(const p of invocations.values()){clearTimeout(p.timer);p.reject(Error('Плагин выключен.'));}invocations.clear();};
 function decode(v:any):any{if(Array.isArray(v))return v.map(decode);if(v&&typeof v==='object'){if(Number.isInteger(v.__callback))return(...args:any[])=>new Promise((resolve,reject)=>{if(disposed){reject(Error('Плагин выключен.'));return;}const id=++sequence;const timer=setTimeout(()=>{invocations.delete(id);reject(Error('Плагин не ответил за 5 секунд. Его можно выключить в настройках.'));},5000);invocations.set(id,{resolve,reject,timer});channel.port1.postMessage({invoke:id,callback:v.__callback,args});});return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,decode(x)]));}return v;}
 const paths=new Set(['atoms.registerDraftPolicy','atoms.list','atoms.get','atoms.create','atoms.update','atoms.setState','atoms.delete','atoms.search','links.list','links.create','links.delete','events.on','commands.add','types.register','graph.registerStructuralProvider','graph.focus','graph.registerLayout','graph.registerPhysicsProvider','graph.registerLayoutProvider','graph.registerClusteringProvider','graph.registerLinkReductionProvider','graph.registerNodeWeightProvider','ui.notify','ui.registerContextAction','views.register','storage.get','storage.set','settings.get','settings.set','assets.list','assets.read']);
 let calls=0;const reset=setInterval(()=>calls=0,1000);
 try{await new Promise<void>((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('Не удалось запустить изолированный плагин.')),10000);channel.port1.onmessage=async({data:m})=>{
 if(m.ready){clearTimeout(timeout);resolve();return;}if(m.fatal){clearTimeout(timeout);reject(Error(m.fatal));return;}
 if(m.invoked){const p=invocations.get(m.invoked);if(p){clearTimeout(p.timer);invocations.delete(m.invoked);m.error?p.reject(Error(m.error)):p.resolve(m.result);}return;}
 try{if(++calls>100)throw Error('Превышен лимит вызовов Plugin API.');let result:any;if(m.path==='dispose'){disposers.get(m.args[0])?.();disposers.delete(m.args[0]);}else{if(!paths.has(m.path)||!Array.isArray(m.args))throw Error('Метод API недоступен.');const [section,method]=m.path.split('.');const fn=(api as any)[section][method];result=await fn(...decode(m.args));}if(typeof result==='function'){const id=++sequence;disposers.set(id,result);result={__dispose:id};}if(!disposed)channel.port1.postMessage({id:m.id,result});}catch(e){if(!disposed)channel.port1.postMessage({id:m.id,error:(e as Error).message});}};
 frame.onload=()=>{const sourceUrlCode=`const sourceURL=URL.createObjectURL(new Blob([${JSON.stringify(source)}],{type:'text/javascript'}));try{const plugin=await import(sourceURL);await plugin.activate(app);postMessage({ready:true});}catch(e){postMessage({fatal:String(e)});}finally{URL.revokeObjectURL(sourceURL);}`;frame.contentWindow!.postMessage(workerBootstrap+'(async()=>{'+sourceUrlCode+'})()','*',[channel.port2]);};});}catch(e){clearInterval(reset);dispose();throw e;}
 return()=>{clearInterval(reset);dispose();};
}};}
