import type {Core} from '../core/core';
import {DIRECT_VAULTS_KEY,migrateObsidianBindings} from '../plugins/obsidian-storage';
import {cacheVaultFiles,exportedNote,importVault,notePath,safePath,splitNote,references,resolveAtom,type VaultFile} from '../core/vault';
import {metadata,readProperties} from '../core/note-metadata';
import {makeAtom,makeLink,type Atom,type Mutation} from '../core/model';
interface Directory extends FileSystemDirectoryHandle {values():AsyncIterableIterator<FileSystemHandle>;requestPermission(options:{mode:'readwrite'}):Promise<PermissionState>}
interface Binding {vault:string;name:string;files:Record<string,{disk:string;local:string}>}
export const directSupported=()=>typeof window!=='undefined'&&'showDirectoryPicker' in window&&typeof FileSystemFileHandle!=='undefined'&&'createWritable' in FileSystemFileHandle.prototype;
async function handleStore(id:string,value?:Directory){const db=await new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open('phosphored-directory-handles',1);request.onupgradeneeded=()=>request.result.createObjectStore('handles');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});try{return await new Promise<Directory|undefined>((resolve,reject)=>{const tx=db.transaction('handles',value?'readwrite':'readonly');const req=value?tx.objectStore('handles').put(value,id):tx.objectStore('handles').get(id);tx.oncomplete=()=>resolve(value||req.result);tx.onerror=()=>reject(tx.error);});}finally{db.close();}}
async function digest(bytes:Uint8Array){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new Uint8Array(bytes)))].map(n=>n.toString(16).padStart(2,'0')).join('');}
const localDigest=(core:Core,a:Atom)=>digest(exportedNote(a,undefined,core.data.links));
async function scan(root:Directory,prefix='',files:VaultFile[]=[]){for await(const entry of root.values()){const path=safePath(prefix+entry.name);if(entry.name==='.phosphored')continue;if(entry.kind==='directory')await scan(entry as Directory,path+'/',files);else{const file=await (entry as FileSystemFileHandle).getFile();files.push({path,bytes:new Uint8Array(await file.arrayBuffer())});if(files.length>30000||files.reduce((sum,f)=>sum+f.bytes.length,0)>512*1024*1024)throw Error('Папка слишком велика для подключения.');}}return files;}
async function fileHandle(root:Directory,path:string,create=false){const parts=safePath(path).split('/');let directory:FileSystemDirectoryHandle=root;for(const part of parts.slice(0,-1))directory=await directory.getDirectoryHandle(part,{create});return directory.getFileHandle(parts.at(-1)!,{create});}
export async function bindings(core:Core){await migrateObsidianBindings(core.storage);return await core.storage.getSetting<Binding[]>(DIRECT_VAULTS_KEY)||[];}
export async function connectVault(core:Core){const root=await (window as unknown as {showDirectoryPicker(options:{mode:string}):Promise<Directory>}).showDirectoryPicker({mode:'readwrite'});const files=await scan(root);const imported=await importVault(core,files,root.name);const binding:Binding={vault:imported.vault,name:root.name,files:{}};for(const a of core.data.atoms.filter(a=>notePath(a)?.vault===binding.vault)){const path=notePath(a)!.path;binding.files[path]={disk:await digest(files.find(f=>f.path===path)!.bytes),local:await localDigest(core,a)};}await handleStore(binding.vault,root);await core.storage.transaction([{kind:'setting',key:DIRECT_VAULTS_KEY,value:[...await bindings(core),binding]}]);return binding;}
export async function syncVault(core:Core,id:string){
 const all=await bindings(core),binding=all.find(b=>b.vault===id);if(!binding)throw Error('Подключение не найдено.');const root=await handleStore(id);if(!root||await root.requestPermission({mode:'readwrite'})!=='granted')throw Error('Разрешите доступ к папке, чтобы синхронизировать заметки. Локальные данные сохранены.');
 const files=await scan(root),disk=new Map(files.map(f=>[f.path,f.bytes])),writes:{path:string;bytes:Uint8Array;expected?:string}[]=[],ops:Mutation[]=[];const nextFiles={...binding.files};
 for(const a of core.data.atoms.filter(a=>notePath(a)?.vault===id)){
  const path=notePath(a)!.path,bytes=disk.get(path),base=binding.files[path],hash=bytes?await digest(bytes):undefined,local=await localDigest(core,a);
  if(base&&!bytes)throw Error('Файл удалён или перемещён вне Phosphored: '+path+'. Локальная заметка сохранена; восстановите файл или экспортируйте хранилище.');
  if(base&&hash!==base.disk){if(hash===await digest(exportedNote(a,bytes,core.data.links))){nextFiles[path]={disk:hash!,local};continue;}if(local!==base.local)throw Error('Конфликт в '+path+': заметка изменена и здесь, и в Obsidian. Обе версии сохранены; согласуйте изменения перед синхронизацией.');const note=splitNote(new TextDecoder().decode(bytes!)),properties=readProperties(note.yaml),fields=metadata(properties);if(fields.id&&fields.id!==a.id)throw Error('Изменился ID заметки: '+path);const atom=makeAtom({...a,...fields,id:a.id,content:note.body,aliases:Array.isArray(properties.aliases)?properties.aliases as string[]:typeof properties.aliases==='string'?[properties.aliases]:[],properties:{...a.properties,...fields.properties,obsidian:properties,tags:properties.tags??[]},revision:a.revision+1,updated_at:new Date().toISOString()});ops.push({kind:'atom',atom,expectedRevision:a.revision});nextFiles[path]={disk:hash!,local:await localDigest(core,atom)};
  }else if(!base||local!==base.local){writes.push({path,bytes:exportedNote(a,bytes,core.data.links),expected:hash});nextFiles[path]={disk:await digest(writes.at(-1)!.bytes),local};}
 }
 for(const file of files.filter(f=>/\.md$/i.test(f.path)&&!binding.files[f.path]&&!core.data.atoms.some(a=>notePath(a)?.vault===id&&notePath(a)?.path===f.path))){const note=splitNote(new TextDecoder().decode(file.bytes)),properties=readProperties(note.yaml);const atom=makeAtom({title:file.path.split('/').at(-1)!.replace(/\.md$/i,''),...metadata(properties),content:note.body,aliases:Array.isArray(properties.aliases)?properties.aliases as string[]:[],properties:{obsidian:properties,tags:properties.tags??[],vault:{vault:id,path:file.path}}});if(core.data.atoms.some(a=>a.id===atom.id))throw Error('Повторяется Phosphored ID: '+file.path);ops.push({kind:'atom',atom});nextFiles[file.path]={disk:await digest(file.bytes),local:await localDigest(core,atom)};}
 const changed=ops.flatMap(op=>op.kind==='atom'?[op.atom]:[]),combined=[...core.data.atoms.filter(a=>!changed.some(b=>b.id===a.id)),...changed];for(const a of changed){const properties=a.properties.obsidian as Record<string,any>;const typed=Array.isArray(properties?.phosphored_links)?properties.phosphored_links:[];const targets=new Set<string>();for(const l of typed)if(combined.some(b=>b.id===l.to)&&l.to!==a.id){targets.add(l.to);ops.push({kind:'link',link:makeLink(a.id,l.to,l.relation||'related',l.source||'markdown')});}for(const ref of references(a.content)){const b=resolveAtom(ref,a,combined);if(b&&b.id!==a.id&&!targets.has(b.id)){targets.add(b.id);ops.push({kind:'link',link:makeLink(a.id,b.id,'related','markdown')});}}for(const l of core.data.links)if(l.from===a.id&&l.source==='markdown'&&!targets.has(l.to))ops.push({kind:'unlink',id:l.id});}
 // Recheck each file immediately before writing. createWritable commits only on close.
 for(const write of writes){const handle=await fileHandle(root,write.path,true);const current=new Uint8Array(await (await handle.getFile()).arrayBuffer());if(write.expected&&await digest(current)!==write.expected)throw Error('Файл изменился во время синхронизации: '+write.path);if(!write.expected&&current.length)throw Error('Файл с таким именем уже существует: '+write.path);const stream=await handle.createWritable();try{await stream.write(new Uint8Array(write.bytes));await stream.close();}catch(e){await stream.abort().catch(()=>{});throw e;}}
 for(const [path,base] of Object.entries(binding.files))if(!core.data.atoms.some(a=>notePath(a)?.vault===id&&notePath(a)?.path===path)){const bytes=disk.get(path);if(!bytes){delete nextFiles[path];continue;}if(await digest(bytes)!==base.disk)throw Error('Удалённая здесь заметка изменена в папке: '+path);const backup=await fileHandle(root,'.phosphored/trash/'+Date.now()+'-'+path,true),stream=await backup.createWritable();await stream.write(new Uint8Array(bytes));await stream.close();const parts=path.split('/');let directory:FileSystemDirectoryHandle=root;for(const part of parts.slice(0,-1))directory=await directory.getDirectoryHandle(part);const current=await fileHandle(root,path);if(await digest(new Uint8Array(await (await current.getFile()).arrayBuffer()))!==base.disk)throw Error('Файл изменился перед удалением: '+path);await directory.removeEntry(parts.at(-1)!);delete nextFiles[path];}
 const written=new Map(writes.map(w=>[w.path,w.bytes]));const cache=files.filter(f=>!/\.md$/i.test(f.path)||combined.some(a=>notePath(a)?.vault===id&&notePath(a)?.path===f.path)).map(f=>({path:f.path,bytes:written.get(f.path)||f.bytes}));for(const write of writes)if(!cache.some(f=>f.path===write.path))cache.push({path:write.path,bytes:write.bytes});ops.push(...await cacheVaultFiles(core.storage,id,cache,combined));
 binding.files=nextFiles;ops.push({kind:'setting',key:DIRECT_VAULTS_KEY,value:all});await core.commit(ops);return {written:writes.length,read:ops.filter(o=>o.kind==='atom').length};
}
